### ISSUE TITLE
The installation exited unsuccessfully -  ERROR: tflite_runtime-2.6.0

### ISSUE THREAD

**Issue by s4en** [mcguirepr89/BirdNET-Pi#1048]
1. Use Rapsberry Imager and install Rasperry Pi OS Lite 64
2. Use Putty to connect with the BirdPi (Raspberry Pi4) in SSH Mode
3. Use the Command `curl -s https://raw.githubusercontent.com/mcguirepr89/BirdNET-Pi/main/newinstaller.sh | bash` to install
4. After a while i got this Error and the Installation stops:

```
 + pip3 install -U -r /home/bird/BirdNET-Pi/requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: tflite_runtime-2.6.0-cp39-none-linux_aarch64.whl is not a supported wheel on this platform.
The installation exited unsuccessfully.

```

**Comment by joostdjong** [comment]
You could try the Pi OS (**Legacy**, 64-bit) Lite version of the **Bullseye** port. It solved the issue for me.

**Comment by s4en** [comment]
> You could try the Pi OS (**Legacy**, 64-bit) Lite version of the **Bullseye** port. It solved the issue for me.

That did the trick.

**Comment by breimann** [comment]
I'm having the same issue, but with the Legacy lite version of Bullseye port...

Help??!!!
