### ISSUE TITLE
Seem to have forgotten username

### ISSUE THREAD

**Issue by MABeatty1978** [mcguirepr89/BirdNET-Pi#1061]
It's been a while since I've logged into my install.  I tried getting into the settings but my login isn't working.  I ssh'd into the box and can see my CADDY_PWD, so I know what the password is.  So all I can assume is that I have the user name wrong.  I don't recall changing the default user at install, but I'm guessing I did as "birder" isn't it.

Is there anyway to get my username/password?

**Comment by Vollpflock** [comment]
have you tried username: birdnet passwort: (nothing)?
