### ISSUE TITLE
birdnet_analysis.sh stuck with "Maximum number of attempts exceeded. Exiting & restarting service."

### ISSUE THREAD

**Issue by arxipelagos** [mcguirepr89/BirdNET-Pi#1099]
When analyzing many detections, it often happens that the birdnet_analysis.sh script gets stuck in the IF loop on line 107. The Pi must then be restarted.
The restart has to be done manually and unfortunately many analyzes are lost until the error is detected.

**Comment by Scraggarax** [comment]
This is something I ran into in error #653. You have to disable the microphone service for the analysis service to catch up and keep refreshing the log.

It seems like getting a larger and/or faster storage might help too.

**Comment by arxipelagos** [comment]
@Scraggarax 
Thanks for the tip.
I'm currently using the Pi with two RTSP streams, so there shouldn't be any problems with the microphone input. I'll try with an external USB.3 NVME. Maybe faster memory will help.

**Comment by Scraggarax** [comment]
It's less of a microphone issue, and More of the way that the analysis system seems to work. If it records more than it processes, it seems to not be able to keep up, so shutting off the recording service until the analysis process catches up prevents it from getting stuck in the loop. You can kinda see what I mean if you watch the logs when it spits it out.

**Comment by arxipelagos** [comment]
Current status:
With the solution of an external NVME storage there are no more failures so far. The files are analyzed much faster and the daily detection rate increases significantly. A clear recommendation not to use an SD card.

**Comment by arxipelagos** [comment]
The system got stuck again.

My approach would now be to start the script “BirdNET-Pi/scripts/restart_services.sh” with the listed error message every time in order to get rid of the accumulated incorrect clips and restart the services properly.
