### ISSUE TITLE
Apprise $flickrimage field is not being passed appropriately

### ISSUE THREAD

**Issue by hestonhamilton** [mcguirepr89/BirdNET-Pi#1140]
**Describe the bug**
Use of the "$flickrimage" variable in the Apprise notification field results in an image of a penguin being returned for all detected species.

I have personally experienced this bug while using Discord webhook integrations but there are recent reports of this issue occurring in MQTT implementations as well:

https://github.com/mcguirepr89/BirdNET-Pi/discussions/342
https://tatageek.blog/2024/02/07/rozpoznani-hlasu-ptaku-pomoci-umele-inteligence/
 
**To Reproduce**
1. Go to Tools > Settings > Notifications in the BirdNET Pi web interface
2. Set Flickr API Key in "Flickr API Key" field under "Bird Photos from Flickr" section.
3. Paste Discord webhook URL in "Apprise Notifications Configuration" field.
4. Use "$flickrimage" anywhere in the "Notification Body" field.
5. Penguin photo below is returned in the Apprise notification for all detected species.

![image](https://github.com/mcguirepr89/BirdNET-Pi/assets/152656464/ffdee3a0-39eb-431a-a8bd-15027ceddc9e)

**Expected behavior**
Use of "$flickrimage" in the Apprise "Notification Body" field should return a photo that matches the detected species.

**Screenshots**

BirdNET Pi settings -

![image](https://github.com/mcguirepr89/BirdNET-Pi/assets/152656464/46299c16-7880-45ee-a631-748dafb4b7c3)

Discord webhook post -

![image](https://github.com/mcguirepr89/BirdNET-Pi/assets/152656464/ec8cd85d-65b0-4e51-8114-ca3d5273b97d)

**Additional context**
Flickr image retrieval works fine everywhere on the web interface, but Apprise Flickr image retrieval seems to be broken.

**Your build**
Raspberry Pi 4

**Comment by TheGingeraffe** [comment]
I was wrong. While this behavior may have been the result of the species not being passed appropriately on test notifications, it seems that everything on the Flickr side works just fine for actual detections.

My only suggestion is to perhaps change the "send test notification" box's command to include the correct species rather than the penguin image for sanity's sake.

![image](https://github.com/mcguirepr89/BirdNET-Pi/assets/37917265/69c3f912-a665-4290-89dd-7579cfdd2709)

**Comment by hestonhamilton** [comment]
I was wrong. While this behavior may have been the result of the species not being passed appropriately on test notifications, it seems that everything on the Flickr side works just fine for actual detections.

My only suggestion is to perhaps change the "send test notification" box's command to include the correct species rather than the penguin image for sanity's sake.

![image](https://github.com/mcguirepr89/BirdNET-Pi/assets/152656464/d1509f9e-c6df-4cde-ad0f-4f901b025049)

Thank you for the wonderful project!
