### ISSUE TITLE
birdnet oiseaux etranger

### ISSUE THREAD

**Issue by PracaRaphael** [mcguirepr89/BirdNET-Pi#1164]
bonjour, 
mon birdnet installé sur un raspberry fonctionne parfaitement mais detecte des oiseaux qui sont pas de chez moi, bien que la geolocalisation (latitude/longitude) est bien chez moi... 
avez vous une solution pour localiser mon birdnet chez moi?
j'ai modifié le ficher birdnet.conf chez moi et je retrouve bien dans la page tool de l'IHM

merci

**Comment by Scraggarax** [comment]
Est-ce-que votre latitude et longitude se sont correct? Peutetre le latitude est dans la longitude section, et les deux se sont melanger. 

Une autre chose que tu peux changé est le modele (BirdNET_GLOBAL_6K_V2.4_Model_FP16 (2023) ou BirdNET_6K_GLOBAL_MODEL (2020)).

Excuse mon français, c'est mon deuxieme langue.

**Comment by PracaRaphael** [comment]
bonjour merci pour ta reponse, et tonnexcelent francais ;o)
oui la longitude/latitude est OK et verifié, et j'ai bien basculé sur le modele 2023...

**Comment by PracaRaphael** [comment]
c'est bon, j'ai fait une modif du modele, un aller/retour et ca fonctionne... (2023 > 2021> 2023)
