### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by bobleposcail** [mcguirepr89/BirdNET-Pi#1185]
Hello,

I am following the install information and get the following error. I have tried twice and get stuck at the same place:

![image](https://github.com/mcguirepr89/BirdNET-Pi/assets/135769852/98bb56f9-c620-440b-9ac0-3eecbc0cfd3a)

thank you for your help

**Comment by Lotwook** [comment]
Make sure you are using 64bit OS. 

The build that got me past this error was Legacy 64-bit Debian Bullseye (note not Bookworm) Lite no Desktop.

**Comment by bobleposcail** [comment]
Perfect. It worked. Thank you very much
