### ISSUE TITLE
Mono or Stereo microphone setup

### ISSUE THREAD

**Issue by SchmidL** [mcguirepr89/BirdNET-Pi#1249]
Hi are there any insights of using a mono or a stereo microphone setup with the BirdNET-Pi?
What would be the pros for a stereo, so far i could not figure out any, besides more data :)

**Comment by tphakala** [comment]
BirdNET Analyzer works with mono files only, if anything stereo could introduce phase issues if stereo channels are downmixed to mono. So mono is recommended.

Btw this repository is abandoned, further development is done on https://github.com/Nachtzuster/BirdNET-Pi
there is also my golang based implementation https://github.com/tphakala/birdnet-go

**Comment by SchmidL** [comment]
Thank you a lot! just saw many stereo setups, but yeah, was not so conclusive for me :)
