### ISSUE TITLE
Problem on PI3B+ 

### ISSUE THREAD

**Issue by gitalm** [mcguirepr89/BirdNET-Pi#130]
Dear Patrick,
Sometimes the analyzing stops.

![grafik](https://user-images.githubusercontent.com/7422149/152981283-70843bd9-fd78-4415-a7d8-e3ed5f1daa9d.png)

**Comment by mcguirepr89** [comment]
Hi, @gitalm  -- could you please check the "System" > "Info" page and let me know what the available storage and memory are?

**Comment by gitalm** [comment]
THanks for the hint, I deactivated BirdWeather and restarted the service. Let's see

**Comment by mcguirepr89** [comment]
It looks like the issue was in _name resolution_, meaning your network connection was not able to come up with an IP address for app.birdweather.com. You might need to set a DNS on your cellular modem for it to resolve domains correctly.

**Comment by gitalm** [comment]
Dear Patrick, the BirdNET Pi was just in  a normal WIFI.
Next step would be to use a cellular modem K5610.
Hope it works out.

Best wishes

**Comment by mcguirepr89** [comment]
Let me know what you find and we'll see what else there might be to look into more closely.

**Comment by gitalm** [comment]
Dear Patrick, it is now working without Problem. I just deleted the BirdWeather ID and restarted. 
The problem is perhaps the weak WIFI signal, therefore the box is a bit away from my house.
Thanks for helping. WIll start the test with cellular modems to be free ;-)
