### ISSUE TITLE
Feature request: Be able to raise extraction and recording length in same settings update

### ISSUE THREAD

**Issue by DD4WH** [mcguirepr89/BirdNET-Pi#145]
if an extraction legth longer than 15 seconds is entered (in the Advanced Settings menu), the entry is not allowed.
the max extraction length should be == Recording length

**Comment by mcguirepr89** [comment]
I'm going to keep this open as a request to be able to set both at the same time -- I'm sure it's possible

**Comment by DD4WH** [comment]
Patrick, thanks a lot for your explanation !!!

It works now using the following workflow:

* Set recording length
* press button "Update Settings"
* Set extraction length
* press same button (now named "Success!")
