### ISSUE TITLE
Species stats does not show

### ISSUE THREAD

**Issue by DD4WH** [mcguirepr89/BirdNET-Pi#147]
On the new page "Species stats":
* this page is not shown in the "mobile" version of the BirdNET-Pi page
* on the standard page version (on my PC): if I choose a species from the dropw-down menu, and press `Show species statistics`, nothing is happening
* maybe language issue? 
* I use locale settings for Gerrmany
* I use German Common names 

--> if I move the mouse over the button `Show species statistics`, the link that is displayed in the lower left corner of the screen is `birdnetpi.local`

![grafik](https://user-images.githubusercontent.com/14326464/154032183-62c63553-a81d-4971-89b2-148c51342abe.png)

**Comment by oliverk71** [comment]
Until now, it is very slow. May have something to do with large images, but even for that it is very slow. 
The way how to figure out which image to load, can be optimized, as this screenshot shows: 
![grafik](https://user-images.githubusercontent.com/10213957/154034155-f7cbcbb3-0f5c-47e8-88a1-92a97fc13c0e.png)
It shows a postcard of "Bad Elster". "Elster" is German for "magpie". ;)

**Comment by DD4WH** [comment]
:-)
Thanks for that hint!
Yes, I can confirm, after ten minutes loading time, my species stats is there !
![grafik](https://user-images.githubusercontent.com/14326464/154034856-332ee437-fd28-4847-8015-1a13b125ce1e.png)

The looking up of webpages and photographs etc. should ALWAYS be based on the SCIENTIFIC NAME.
