### ISSUE TITLE
Birdnet analysis stops 

### ISSUE THREAD

**Issue by oliverk71** [mcguirepr89/BirdNET-Pi#164]
On my installation (3B, main), it happens quite often, that birdnet analysis stops. Today it stopped around 4:20 in the night (now, it is 9:20 here, so it stopped 5 hours ago). If I restart the service, it catches up.

**Comment by mcguirepr89** [comment]
I'm very sorry to hear that, Oliver. Can you please provide more information, e.g., a log excerpt, verification of which branch, any and all customizations your installation may have.

Thank you,
Patrick

**Comment by oliverk71** [comment]
It's my public birdnet-pi, you can login if you want. It is an installation of main v.0.11.1, updated regularly. No customizations except the swap, which you did.

**Comment by mcguirepr89** [comment]
Thanks, I will see what I can find

**Comment by mcguirepr89** [comment]
Hello, again -- it looks like the _server_ stopped because it was not able to POST to BirdWeather. Not being able to POST to BirdWeather shouldn't result in such a fatal error. I'm about 90% I've fixed this in `sqlite`, but I'm double checking now

**Comment by mcguirepr89** [comment]
I am testing a new change to `server.py` now that will `try:` the POST and will throw an exception otherwise. I'm very hopeful those changes will prevent that kind of issue from stopping the service altogether.

Thank you again for letting me know what you observed and for allowing me remote access to your system to take a closer look -- it is very valuable!
My best,
Patrick

**Comment by oliverk71** [comment]
Just restarted service and now it is not even catching up, it just starts analyzing at restart time which means that already recorded data is not being considered. Bad.

**Comment by mcguirepr89** [comment]
Same error. Thanks, the fix will be ready when I have one and it has been tested.

**Comment by mcguirepr89** [comment]
Hi, Oliver -- sorry for the delay in this response, but I should I have let you know I put a fix in place for this in the `newif` branch that will be `main` after more testing. https://github.com/mcguirepr89/BirdNET-Pi/commit/579d3b1e26cbe156703f9f606aa302e06df33ddf scroll down to the commit for `scripts/server.py`.

I'll keep this open until `newif` is pulled into `main` and merged.

Thanks again and best regards,
Patrick

**Comment by oliverk71** [comment]
Hi Patrick! This are good news! By the way: it never happened with my pi for testing, running the sqlite version. However, may be that I just did not recognize it. 
I had a look on the scripts/server.py, and it seems that just the try: and except: which is added, right? 
Can't wait until the newif is merged into main. Good work, Patrick! Thanks again for all your work!
