### ISSUE TITLE
Minor issue: Species detected today --> wrong link

### ISSUE THREAD

**Issue by DD4WH** [mcguirepr89/BirdNET-Pi#179]
Overview page:
* in the table at the left side of the page: if I click on the number of "Species Detected Today", I am redirected to the page wit ALL the species detected
* it should be the page with only the species detected today

**Comment by mcguirepr89** [comment]
Great catch! I'll let you know when an update will fix that link for you :+1:

**Comment by mcguirepr89** [comment]
Alright, I've made this change. Go ahead and do an update via "Tools" > "System Controls" > "Update" and then let me know if that link target is what you had in mind.

**Comment by mcguirepr89** [comment]
Howdy, @DD4WH -- I just wanted to follow up on this to see if I've fixed the target the way you had in mind. To me, it now makes more sense where those links take you.

**Comment by DD4WH** [comment]
Sorry for my late reply! I missed your fix and your response!
YES, now the link goes to the right page!
Thank you!
