### ISSUE TITLE
Solved: Trouble installing on a headless Pi with a remote desktop from Windows

### ISSUE THREAD

**Issue by nilspupils** [mcguirepr89/BirdNET-Pi#20]
Hi everyone, 

i tried numerous times again and i cannot get the installer to work, also tried the rpialpha one with the same result. 
The installer always stops after i insert my location, save and close the editor. 
Then it just hangs there and nothing happens. If i iterrupt with ctrl-c it then says: 

^Csed: can't read /home/pi/BirdNET-Lite/birdnet.conf: No such file or directory
Your compressed logs are located at /home/pi/BirdNET-Lite/logs.tar.gz
sed: can't read /home/pi/BirdNET-Lite/birdnet.conf: No such file or directory
Your compressed logs are located at /home/pi/BirdNET-Lite/logs.tar.gz

So this is a rundown of everything i do when i start from scratch: 

Burn 2021-05-07-raspios-buster-arm64 with the Raspberry Pi Imager on a 32GB SD in Windows. 
Boot with the Pi. SSH into the Pi from a Windows machine. 
sudo apt-get install tightvncserver --yes
sudo apt-get install xrdp --yes
reboot
Open a remote desktop with the Pi from the windows machine.
curl -s https://raw.githubusercontent.com/mcguirepr89/BirdNET-Lite/rpi4/Birders_Guide_Installer.sh | bash
Then it updates quite a bit, then reboots.
again: 
curl -s https://raw.githubusercontent.com/mcguirepr89/BirdNET-Lite/rpi4/Birders_Guide_Installer.sh | bash
Then it opens mousepad, i insert location data, passwords, save and close. 
Then i am stuck....
It seems not to be able to read the configfile, and is waiting for the editor to finish. 

Even when i reboot, start the script again, still stuck at the same step.
Do you have an idea what's happening? 
It is probably something really simple that i am missing, as i am quite new to RPi and linux....
Thanks a million and best regards, 

Nils

**Comment by nilspupils** [comment]
Hi Patrick, 
thanks for the detailed answer. I have looked into the remote desktop again and it seems windows doesn't use VNC but XRDP for its remote desktop. This is most likely the reason for all the trouble.
So i will try to connect via VNC with another software. I will check this right now. 
Thanks for pointing me in the right direction!

**Comment by mcguirepr89** [comment]
[Try this ](https://www.realvnc.com/en/connect/download/viewer/windows/)
