### ISSUE TITLE
High traffic spikes lock the DB

### ISSUE THREAD

**Issue by mcguirepr89** [mcguirepr89/BirdNET-Pi#206]
With the recent visitor traffic on my Virginia BirdNET-Pi test system, I've noticed that a huge spike (+1,000 visits in an hour so far as I can see right now) can lock up the database. I just wanted to document this to take a look at once this crazy traffic spike has subsided a little. I suppose I'll just handle that with a better `except`ion than the current one that handles a busy database. The logs will know what we should do, so I'll post what I find therein soon

**Comment by ehpersonal38** [comment]
I've just submitted a PR to partially address this. It merges 3 DB queries into one and handles the data analysis with a for loop instead, and reduces overall queries by only loading the ones each AJAX function needs (before, the newest detection updating would execute like 5 DB calls even though it didn't need that data at all).

**Comment by mcguirepr89** [comment]
Cool I merged this as its just obviously better :) thanks for your amazing volume of tweaks and fixes -- I think I'm missing the copy link on my overview page right now -- do you see it on your end?

**Comment by ehpersonal38** [comment]
> Cool I merged this as its just obviously better :) thanks for your amazing volume of tweaks and fixes -- I think I'm missing the copy link on my overview page right now -- do you see it on your end?

You're welcome!

I did remove the copy link on the overview page, as the scientific name of the species was overflowing into the copy button if it was too long... but if you'd like it back I suppose you can just `<br>` between the common name and scientific name, like it is on Today's Detections

**Comment by mcguirepr89** [comment]
Yes I see now -- :+1: I'll keep things as is for now!

**Comment by mcguirepr89** [comment]
I've been watching the database lock go down for a little while now and am pretty sure that just adding the`try:` `except:` is handling the high traffic without breaking the service -- if the database is locked, it just moves on -- I'll probably go back and make it try to enter the database entry again instead of just moving on, but for now I just want to _fix_ the service breaking. You'll see the new push come through soon that adds the `try:` and `except:` blocks
