### ISSUE TITLE
BirdNET-Pi stops processing/analyzing at midnight (1)

### ISSUE THREAD

**Issue by DavePoortvliet** [mcguirepr89/BirdNET-Pi#214]
First off, I LOVE this project, great work! I have been so geeked about this and telling my family and friends, many of them roll their eyes at the nerdiness of it all :) Sorry, I know you have a lot of requests and I am happy to troubleshoot myself if there are any resources you can point me to. Everything seems to be up and running smoothly however it stopped detecting. I've restarted all services and pulled the latest version. Log below. Let me know what else I can provide. 

```
0:25:44 systemd[1]: birdnet_analysis.service: Consumed 4.424s CPU time.
10:25:44 systemd[1]: Started BirdNET Analysis.
10:25:45 birdnet_analysis.sh[38251]: Files loaded
10:25:56 systemd[1]: birdnet_analysis.service: Succeeded.
10:25:56 systemd[1]: birdnet_analysis.service: Consumed 4.384s CPU time.
10:25:58 systemd[1]: birdnet_analysis.service: Scheduled restart job, restart counter is at 216.
10:25:58 systemd[1]: Stopped BirdNET Analysis.
10:25:58 systemd[1]: birdnet_analysis.service: Consumed 4.384s CPU time.
10:25:58 systemd[1]: Started BirdNET Analysis.
10:25:59 birdnet_analysis.sh[38402]: Files loaded
10:26:10 systemd[1]: birdnet_analysis.service: Succeeded.
10:26:10 systemd[1]: birdnet_analysis.service: Consumed 4.501s CPU time.
10:26:12 systemd[1]: birdnet_analysis.service: Scheduled restart job, restart counter is at 217.
10:26:12 systemd[1]: Stopped BirdNET Analysis.
10:26:12 systemd[1]: birdnet_analysis.service: Consumed 4.501s CPU time.
10:26:12 systemd[1]: Started BirdNET Analysis.
10:26:13 birdnet_analysis.sh[38568]: Files loaded
10:26:24 systemd[1]: birdnet_analysis.service: Succeeded.
10:26:24 systemd[1]: birdnet_analysis.service: Consumed 4.395s CPU time.
10:26:26 systemd[1]: birdnet_analysis.service: Scheduled restart job, restart counter is at 218.
10:26:26 systemd[1]: Stopped BirdNET Analysis.
10:26:26 systemd[1]: birdnet_analysis.service: Consumed 4.395s CPU time.
10:26:26 systemd[1]: Started BirdNET Analysis.
10:26:27 birdnet_analysis.sh[38726]: Files loaded
10:26:37 systemd[1]: birdnet_analysis.service: Succeeded.
10:26:37 systemd[1]: birdnet_analysis.service: Consumed 4.401s CPU time.
10:26:40 systemd[1]: birdnet_analysis.service: Scheduled restart job, restart counter is at 219.
10:26:40 systemd[1]: Stopped BirdNET Analysis.
10:26:40 systemd[1]: birdnet_analysis.service: Consumed 4.401s CPU time.
10:26:40 systemd[1]: Started BirdNET Analysis.
10:26:41 birdnet_analysis.sh[38884]: Files loaded
```

**Comment by ehpersonal38** [comment]
Does the live stream audio in the top right work? Is there sound?

**Comment by ehpersonal38** [comment]
> yes

Okay then I'm not sure, you'll have to wait for Patrick to respond (the creator).

In my experience as a user I've been able to fix problems with this:
1) In console, type git pull
2) In BirdNet-Pi web interface, go to Tools -> System Controls -> Update
3) Reboot the device

Again if that doesn't work hopefully Patrick or someone else will chime in. Hope you get it running soon!

**Comment by DavePoortvliet** [comment]
Thank you for the quick response! I'll give these try and report back.

**Comment by DavePoortvliet** [comment]
no luck :(

**Comment by ehpersonal38** [comment]
> no luck :(

Darn! Well if you'd like to troubleshoot on your own, I can offer you a snippet of what a successful log looks like:
```
11:58:50 systemd[1]: Started BirdNET Analysis.
11:58:52 birdnet_analysis.sh[139092]: Files loaded
11:58:54 birdnet_analysis.sh[139092]: RECORDING_LENGTH set to 15
11:59:01 birdnet_analysis.sh[139092]: analyze.py --i /home/pi/BirdSongs/April-2022/20-Wednesday/2022-04-20-birdnet-11:58:45.wav --o /home/pi/BirdSongs/April-2022/20-Wednesday/2022-04-20-birdnet-11:58:45.wav.csv --lat {redacted)--lon (redacted) --week 15 --overlap 0.0 --sensitivity 1 --min_conf 0.7 --exclude_list /home/pi/BirdNET-Pi/exclude_species_list.txt
11:59:01 server.py[404]: ANALYZING AUDIO... DONE! Time 1.9 SECONDS
11:59:01 server.py[404]: WRITING RESULTS TO /home/pi/BirdSongs/April-2022/20-Wednesday/2022-04-20-birdnet-11:58:30.wav.csv ... DONE! WROTE 0 RESULTS.
11:59:01 server.py[404]: [NEW CONNECTION] ('127.0.0.1', 34050) connected.
11:59:01 server.py[404]: [ACTIVE CONNECTIONS] 1
11:59:01 server.py[404]: READING AUDIO DATA... DONE! READ 5 CHUNKS.
11:59:01 server.py[404]: FULL FILENAME: -/home/pi/BirdSongs/April-2022/20-Wednesday/2022-04-20-birdnet-11:58:45.wav-
11:59:01 server.py[404]: Date-time: 2022-04-20 11:58:45
11:59:03 birdnet_analysis.sh[139318]: 0.0;3.0-("Peucaea aestivalis_Bachman's Sparrow", 0.022720357)
11:59:03 birdnet_analysis.sh[139318]: 3.0;6.0-('Rallus crepitans_Clapper Rail', 0.017098928)
11:59:03 birdnet_analysis.sh[139318]: 6.0;9.0-("Peucaea aestivalis_Bachman's Sparrow", 0.019922316)
11:59:03 birdnet_analysis.sh[139318]: 9.0;12.0-("Peucaea aestivalis_Bachman's Sparrow", 0.014995)
11:59:03 birdnet_analysis.sh[139318]: 12.0;15.0-("Peucaea aestivalis_Bachman's Sparrow", 0.01814498)
11:59:03 systemd[1]: birdnet_analysis.service: Succeeded.
11:59:03 systemd[1]: birdnet_analysis.service: Consumed 2.640s CPU time.
11:59:06 systemd[1]: birdnet_analysis.service: Scheduled restart job, restart counter is at 17886.
11:59:06 systemd[1]: Stopped BirdNET Analysis.
11:59:06 systemd[1]: birdnet_analysis.service: Consumed 2.640s CPU time.
```

It looks like yours fails somewhere in birdnet_analysis.sh after "Files loaded," and before "analyze.py" is called. Best of luck, hopefully Patrick can help later

**Comment by mcguirepr89** [comment]
Hi guys -- I'm no longer supporting this project -- but this was the last thing to pop into my GitHub notifications, so I will address it.

First, try "Tools" > "Services" > "Restart ALL Services" and be very patient while it does so. The page will seem like nothing is happening, but there is a lot going on under the hood. You'll see a dump of the "Restart ALL Services" button when it has completed. Snag a copy of its output and place that here for me to take a quick look through.

If the restart was successful, you'll notice in your logs right away. If not, I'll ask for more info.

My best regards,
Patrick
PS
Thanks @ehpersonal38 for your assistance and attempt to answer this issue, I hope you will continue to choose to help going forward

**Comment by mcguirepr89** [comment]
Also, @ehpersonal38 -- I removed the `main` branch protection rule, so you're welcome to make any changes to the repo you see fit without my review (or any review). I just wanted to let you know so that you dont' wait for me.

**Comment by ehpersonal38** [comment]
> Hi guys -- I'm no longer supporting this project -- but this was the last thing to pop into my GitHub notifications, so I will address it.
> 
> First, try "Tools" > "Services" > "Restart ALL Services" and be very patient while it does so. The page will seem like nothing is happening, but there is a lot going on under the hood. You'll see a dump of the "Restart ALL Services" button when it has completed. Snag a copy of its output and place that here for me to take a quick look through.
> 
> If the restart was successful, you'll notice in your logs right away. If not, I'll ask for more info.
> 
> My best regards, Patrick PS Thanks @ehpersonal38 for your assistance and attempt to answer this issue, I hope you will continue to choose to help going forward

Wow -- that's really shocking to hear. Hopefully the person who takes over this repo will continue building up what you created. 

I wish you the very best of luck in whatever comes next for you!
-Ethan

**Comment by mattvlr** [comment]
It might be a time zone issue if the raspberry pi is ahead of your local time. This happened to me yesterday, I live in UTC -6 so at 6pm yesterday the pi flipped to the next day. At that point my log looked a lot like the initial screenshot.

I fixed this by using `sudo raspi-config` in the web terminal. That should let you select the correct time zone. I did however have to wait until 12am local time for everything to resync.

Hope this helps
-Matt

**Comment by DavePoortvliet** [comment]
oh! Thanks, I will give that a shot!

**Comment by mcguirepr89** [comment]
Hi, @DavePoortvliet -- Any luck with restarting services? Any output to share?

**Comment by DavePoortvliet** [comment]
Thanks for the follow-up. Haven't had time to get back to it, hoping to this weekend. I'll report back my findings & output.

**Comment by DavePoortvliet** [comment]
Was able to get it back up and running, however, after about an hour it is flooding my network with traffic and actually causing my home network to crawl, and slowing down the send/receive for detections to the point it stops again. I'll keep digging.

**Comment by mcguirepr89** [comment]
Hi, @DavePoortvliet 

>after about an hour it is flooding my network with traffic and actually causing my home network to crawl, 

This part is alarming, as there is nothing in BirdNET-Pi that sends out network traffic that is not requested (unless you have enabled BirdWeather integration, which does POST each detection to their server). 

It merely _listens_ on ports 21 (FTP), 22 (SSH), 80 (HTTP), 443 (HTTPS), 5050 (`server.py`'s socket)[`localhost` only], 8000 (IceCast2)[`localhost` connections only], 8080 (GoTTY)[`locahost` only], 8501 (Streamlit's web server)[`localhost` only] and 8888 (GoTTY)[`localhost` only].

If you're seeing packets coming from the BirdNET-Pi that you haven't requested, I would **_immediately_** take it off of your network.

Logs, however, will tell us what is going on, so please feel free to send the output of some logs as you are monitoring your network (I recommend using WireShark to watch things move around) and the system (`/var/log/syslog`).

**Comment by DavePoortvliet** [comment]
Thanks for the port info, very helpful. On it! I will report back.

**Comment by filikun** [comment]
> Hi guys -- I'm no longer supporting this project

Nooo, what happens now?

**Comment by mcguirepr89** [comment]
Please reference this for updates to this issue https://github.com/mcguirepr89/BirdNET-Pi/issues/218#issuecomment-1107832097

**Comment by mcguirepr89** [comment]
Hello, I'm closing this issue per [the most recent push.](https://github.com/mcguirepr89/BirdNET-Pi/commit/a8fb4c79a6574bd0272fff1f0b59ce2b2777330e) Please open another issue if you encounter anything else that needs attention. 

My best,
Patrick
