### ISSUE TITLE
Privacy_server.py unable to start

### ISSUE THREAD

**Issue by sercanacar** [mcguirepr89/BirdNET-Pi#221]
Hi,

Thank you for the amazing project. I had the birdnet running absolutely, disk filled up and I thought I would give a restart but not it errors with

```Traceback (most recent call last):
  File "/home/pi/BirdNET-Pi/scripts/./privacy_server.py", line 10, in <module>
    import tflite_runtime.interpreter as tflite
  File "/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 27, in <module>
    import numpy as np
  File "/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages/numpy/__init__.py", line 143, in <module>
    from . import lib
  File "/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages/numpy/lib/__init__.py", line 25, in <module>
    from .index_tricks import *
ModuleNotFoundError: No module named 'numpy.lib.index_tricks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/BirdNET-Pi/scripts/./privacy_server.py", line 12, in <module>
    from tensorflow import lite as tflite
ModuleNotFoundError: No module named 'tensorflow'
```

Not sure how that broke though

Regards

**Comment by mcguirepr89** [comment]
Hi, @sercanacar -- thanks for installing BirdNET-Pi. I'm glad you were able to use it until your disk filled up, though the system should have handled the full disk by removing old data (by default, unless you changed the "Full Disk" behavior in "Advanced Settings").

Is you disk still full?
Could you please provide the output of ```df -h```?

**Comment by CaiusX** [comment]
Hi @sercanacar 

Looks as if you may have lost something in Python tflite/tensorflow/numpy.  I suggest backing up your database and sound files and trying a clean reinstall, or more tricky, reinstall Numpy and the PINTO binaries.

**Comment by sercanacar** [comment]
Thank you for the replies.

@CaiusX  I had to reinstall and its working again. I was trying to enable Privacy Mode, wondering if that didn't go well...

@mcguirepr89  Default setting for `Full Disk Behavior:` is Purge, but doesn't seem to work for me...disk fills up and pi comes to a stop...not sure how its trying to perform a purge if the OS has no free disk available to run anything more...include rm

**Comment by sercanacar** [comment]
8GB...don't shoot me...times are hard
________________________________

**Comment by CaiusX** [comment]
Hmmm, lets see what we can do, did you install OS or OS_lite?  Memory wise lite would be better.

What does your Tools/System Info Mounted Filesystems report?  I have just installed the full OS on a 16GB card, and it only shows 8.42 free - not much wiggle room....

**Comment by ehpersonal38** [comment]
I just tested the Full Disk Behavior: purge and can confirm it works as expected.

What I'd recommend to you:
1. Try running `bash /home/pi/BirdNET-Pi/scripts/disk_check.sh` and see if there's any errors or weird behavior. My output for <95% disk full is:

```
pi@birdnetpi:~/BirdNET-Pi/scripts$ bash /home/pi/BirdNET-Pi/scripts/disk_check.sh
++ df -h /
++ tail -n1
++ awk '{print $5}'
+ used=84%
+ '[' 84 -ge 95 ']'
+ sleep 1
+ '[' 84 -ge 95 ']'
```

and 95% or above is:
```
...
(first part of the output was lost to Putty)
removed '/home/pi/BirdSongs/Extracted/By_Date/2022-04-17/Northern_Cardinal/Northern_Cardinal-51-2022-04-17-birdnet-09:56:30.mp3'
removed '/home/pi/BirdSongs/Extracted/By_Date/2022-04-17/Northern_Cardinal/Northern_Cardinal-59-2022-04-17-birdnet-16:20:45.mp3.png'
removed '/home/pi/BirdSongs/Extracted/By_Date/2022-04-17/Northern_Cardinal/Northern_Cardinal-51-2022-04-17-birdnet-09:56:30.mp3.png'
removed '/home/pi/BirdSongs/Extracted/By_Date/2022-04-17/Northern_Cardinal/Northern_Cardinal-86-2022-04-17-birdnet-10:00:00.mp3.png'
removed '/home/pi/BirdSongs/Extracted/By_Date/2022-04-17/Northern_Cardinal/Northern_Cardinal-67-2022-04-17-birdnet-16:06:24.mp3'
```

2. If there's no weird errors and the file above executes normally, then I'd suspect a cron issue. Check `/etc/crontab` for references to "disk_check.sh", or verify cron is even running with `service cron status`

**Comment by mcguirepr89** [comment]
Hi, I wanted to circle back to this since I never really was involved -- any luck getting things to work on the 8GB SD card?

If its just simply a no-go on an 8GB SD card, you might be able to do away with `pulseaudio` and just use `ALSA` -- it will require more post-installation configuration, but will not install the huge list of libraries that get installed alongside `pulseaudio`. It would also require a small tweak to `birdnet_recording.sh` to comment out the line that starts `pulseaudio`.

Just some thoughts in an effort to get this working for you on the hardware to which you have access.

Do keep us posted, otherwise I'll need to close this issue from inactivity.

My best regards,
Patrick
