### ISSUE TITLE
PRIVACY_MODE is "on" but I'm still getting recordings with human voices

### ISSUE THREAD

**Issue by jmherbst** [mcguirepr89/BirdNET-Pi#227]
Hello,

I've enabled privacy mode, but I'm still getting some recordings with my family's voices in the background if we are eating outside.  The voices are very low, and in the faint background, but somewhat audible.  

Is there anything I can do to troubleshoot or tune `PRIVACY_MODE`? 

(loving the app so far!) Thanks!

**Comment by ehpersonal38** [comment]
The BirdNET model does have some capacity to detect human voices, but as it is a bird prediction model I'd imagine that wasn't the top of their priorities--so false positives are to be expected. However, if you go to "View Logs" you can watch the analysis return "Human" whenever it thinks it hears a human, so you could use that for debugging and testing?

**Comment by CaiusX** [comment]
hi @jmherbst 

Great you're enjoying the system!

The privacy mode works that when the algorithm sees a "Human" in the top 100 recognitions in a particular sample, it doesnt report anything for that sample - you can check that is working by View Log and talking around the mic:

![image](https://user-images.githubusercontent.com/25373276/165800917-abd2ed93-e591-45c9-b86a-db0a4cbd2e97.png)

you should get Human Detected warnings.

You can change the "sensitivity" by making the number greater than 100 in "privacy_server.py" here:

![image](https://user-images.githubusercontent.com/25373276/165802063-ce428abd-1fd0-46cf-a6e6-d3369dd9ab7f.png)


I tend to find 100 is more than adequate.

Please note that this wont delete audio files with voices  in the "Processed" directory, but these are cleaned out on a  rolling 2 hr basis and aren't directly accessible from the interface.

Hope this helps, shout if you need any further help.

Best

**Comment by jmherbst** [comment]
Thanks for the troubleshooting details @ehpersonal38 and @CaiusX! This is helpful and I was able to at least view logs and test + confirm detection is working. I'll try to fiddle a bit with the "sensitivity" maybe.
