### ISSUE TITLE
Notification loop

### ISSUE THREAD

**Issue by mcguirepr89** [mcguirepr89/BirdNET-Pi#264]
Help!!! My phone's notification sound is an Carolina Chickadee. I've configured BirdNET-Pi to send notifications for every detection. My phone is near my BirdNET-Pi. It won't stop!!!
Help!!

JK :)

It's just fun to put jokes in the issues cuz why not?!?!?!

**Comment by ehpersonal38** [comment]
To fix this issue, I think we should try developing a model to determine if bird sounds are coming from a phone speaker or not - then we can ignore them if so. Much like how privacy mode is implemented. 🐦

**Comment by CaiusX** [comment]
Rather loop an endangered specie and do your bit for increasing its population.
