### ISSUE TITLE
My favorite issue of all time

### ISSUE THREAD

**Issue by mcguirepr89** [mcguirepr89/BirdNET-Pi#314]
![image](https://user-images.githubusercontent.com/60325264/170292177-f471bd78-159f-49cc-908a-04b71c7c1ff9.png)
![image](https://user-images.githubusercontent.com/60325264/170292251-d465d824-ea45-44be-bade-9c87b2574539.png)
![image](https://user-images.githubusercontent.com/60325264/170292317-d9321d31-c488-4778-9bd4-3501e052e66b.png)
![image](https://user-images.githubusercontent.com/60325264/170293612-cfbe34a0-1ffe-4204-8514-ee625dc89751.png)
![image](https://user-images.githubusercontent.com/60325264/170294383-9a2db8dc-af8c-4c16-9554-8faa2845c9ca.png)

:rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl:

**Comment by ehpersonal38** [comment]
Hahahahaha!! Thanks for the bug report!
