### ISSUE TITLE
Overview page doesnt reset top 10 at midnight 

### ISSUE THREAD

**Issue by b0rnwr0ng** [mcguirepr89/BirdNET-Pi#341]
The page automatically refreshes when new detections are made, along with the top 10 graph, but once the day is filled at misnight you need to refresh the page so that graph goes back and shows the earlier times.

**Comment by b0rnwr0ng** [comment]
Everything updates except for the top 10 table.  Once you refresh the page the table is refresh correctly.

I'll take a photo tomorrow morning

**Comment by ehpersonal38** [comment]
Okay, that's very strange. If you could also leave the developer console open ( CTRL + SHIFT + I ) so we can see if any errors pop up when it hits midnight.

**Comment by b0rnwr0ng** [comment]
I didn't see this message, I'll try that tonight, screen shots below

**Comment by b0rnwr0ng** [comment]
![20220602_081945](https://user-images.githubusercontent.com/15163940/171632281-dcc82329-3ce2-4bd7-a122-d15e9f6b8323.jpg)
Before refresh (top 10 didn't update but everything else does)

**Comment by b0rnwr0ng** [comment]
![20220602_081957](https://user-images.githubusercontent.com/15163940/171632484-026e6404-2745-44b9-9586-ba65dbaf7d8c.jpg)
Everything up to date once i refresh the page

**Comment by ehpersonal38** [comment]
@mcguirepr89 Does anything happen at 11:57 PM that would be applicable to the daily plot?

**Comment by mcguirepr89** [comment]
Hi -- I think this is because `overview.php` sets its date when it is loaded, and that is the Chart image for which it looks.

https://github.com/mcguirepr89/BirdNET-Pi/blob/c876c837e5d1add95740f9d6711ffb0c9bd4a9bf/scripts/overview.php#L7

**Comment by b0rnwr0ng** [comment]
Not that I'm aware of, but i can't confirm either way.

**Comment by ehpersonal38** [comment]
Right you are! Thanks for that.

Fixed in 0e00b55ab02848bf27e5f071dcd918b3ecd9c53c.

**Comment by b0rnwr0ng** [comment]
Thanks!

**Comment by mcguirepr89** [comment]
Thank you!

**Comment by ehpersonal38** [comment]
Okay, this one should work. It gets its date for the chart that it's supposed to load directly from the server, same as a refresh would. Let me know how it works for you 🐤
