### ISSUE TITLE
Excluded species list Alberts Lyrebird.

### ISSUE THREAD

**Issue by Jerrajerra** [mcguirepr89/BirdNET-Pi#348]
**Describe the bug**
Alberts Lyrebird is still being detected after being added to the excluded species list

Noticed that whole name does not move across when added

![image](https://user-images.githubusercontent.com/3050172/171991898-1c134a50-3d2e-40bc-9c6d-37e47e7c70ad.png)
![image](https://user-images.githubusercontent.com/3050172/171991941-0a17f7f1-ee69-417c-987e-6df176009804.png)

Thankyou

**Comment by mcguirepr89** [comment]
Thanks for letting me know! [I put a fix in place](https://github.com/mcguirepr89/BirdNET-Pi/commit/045afcdd11b15359ed24aab8ccef8c5123a9211c) for that and it should work now -- if you could please update and then test, I would appreciate it greatly!

"Tools" > "System Controls" > "Update"

**Comment by mcguirepr89** [comment]
Also, unrelated:
@ehpersonal38 let's squash this -- I'm better you'll know how to address the menu bar letting text escape as in the "Tools" button in this screenshot
![image](https://user-images.githubusercontent.com/60325264/171996705-0542fbeb-d2b1-40e0-8713-92a6e1c65a38.png)

If you have initial ideas, I'll gladly take a look

**Comment by ehpersonal38** [comment]
There you are - b24d8d9796dd32df196294cb8b8fc2d31cb47f6f. I didn't know you could do that with CSS, so thanks for letting me learn that! 🙂

**Comment by mcguirepr89** [comment]
Thank you!!!!! And likewise!! I always learn something from your commits ~~

**Comment by Jerrajerra** [comment]
updated  and monitoring. Will load the dishwasher straight after a Bower bird calls to apparently replicate a Lyrebird. 
Thankyou again for a great project
