### ISSUE TITLE
cannot access web terminal due to unrecognized credentials.

### ISSUE THREAD

**Issue by johnocampbell99** [mcguirepr89/BirdNET-Pi#366]
Whenever I try to connect to the web terminal, it prompts me with:

birdnetpi login:

I use the default credentials I used when setting up birdnetpi but they are not recognized and I cannot proceed using the terminal.  It just provides: Login incorrect

I should note I was able to access the terminal recently.  Just ran into this issue this morning

**Comment by ehpersonal38** [comment]
Does this happen when you ssh in (either with Putty if you're on windows, or terminal on Linux), or is it just the web terminal?

**Comment by mcguirepr89** [comment]
Please check your capslock -- unfortunately, their won't be much we can do to help you recall your system credentials.

**Comment by johnocampbell99** [comment]
my apologies, you can remove this.  Or I will try to.  It's very early and my head must not be on straight.  I resolved the issue
