### ISSUE TITLE
Other Bird titles

### ISSUE THREAD

**Issue by TheBigBottle** [mcguirepr89/BirdNET-Pi#367]
Hey there, 
i would like to be able to change the bird names into other languages. 
Maybe we could Start a side Projekt for the translations. 

Thanks for your work!!!! 

Kind regards and stay safe !!!

**Comment by mcguirepr89** [comment]
Hello again -- [please read the documentation on the projects main readme](https://github.com/mcguirepr89/BirdNET-Pi#internationalization) -- if you have updates to the translations you can submit them as a pull request
