### ISSUE TITLE
APPRISE_NOTIFY_NEW_SPECIES not sending notification on first detection

### ISSUE THREAD

**Issue by joeweiss** [mcguirepr89/BirdNET-Pi#388]
In `server.py`, `sendAppriseNotifications` is called after results are written to file, but before the database is updated. 

This results in `APPRISE_NOTIFY_NEW_SPECIES` notifications not being sent until the second detection of the bird occurs, since the code to check for a new species's appearance queries the db.

https://github.com/mcguirepr89/BirdNET-Pi/blob/main/scripts/server.py#L259-L277

**To Reproduce**
1. Enable APPRISE_NOTIFY_NEW_SPECIES
2. Detect new species only once
3. Note that apprise notification is not sent

**Expected behavior**
Expected that notification would be sent.

**Additional context**

I'm interested in adding something like `APPRISE_NOTIFY_NEW_SPECIES_DAILY` to send a notification of the first appearance of a bird each day. I noticed that my rough implementation wasn't working on first detection due to this issue. If you're interested in taking a PR for something like this "first of this species today" notification, please let me know. 

And thanks for all your work!

**Comment by ehpersonal38** [comment]
Right you are! Thanks for this specific and detailed bug report! I just issued a commit and it seems to be working in testing, but be sure to report back if it still causes issues for you.

As for the PR on a possible `APPRISE_NOTIFY_NEW_SPECIES_DAILY`, I'd gladly accept that. I think the more customization the better, and why not add it to the public repo?

 🐤
