### ISSUE TITLE
Notification Body Doesn't Accept JSON Formatting

### ISSUE THREAD

**Issue by mcguirepr89** [mcguirepr89/BirdNET-Pi#398]
I read the docs, I swear!!!
@sjg
I'm working on this in the `json_notification_body` branch -- I'll let you know how the testing goes -- if it's successful, you'll be able to update to try and get JSON formatted output. Don't worry, though -- we'll get this feature for sure

**Comment by mcguirepr89** [comment]
@sjg, can you please provide a JSON string example you'd want to send?

Thank you!

**Comment by sjg** [comment]
:) Lets close this issue as you're working on it in the other one on the other branch :)
