### ISSUE TITLE
Add the ability to notify on species' first detection of the day

### ISSUE THREAD

**Issue by joeweiss** [mcguirepr89/BirdNET-Pi#401]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to receive a notification on the first detection of the day for each species. The alert should be configurable by setting `APPRISE_NOTIFY_NEW_SPECIES_EACH_DAY` to `1` in the .conf file. 

**Describe alternatives you've considered**
N/A

**Additional context**
I've implemented this and I'll open a PR with the code shortly.

**Comment by ehpersonal38** [comment]
@joeweiss Those commits were done in a separate branch from main, so I believe your PR can still be accepted without much conflict. Just put the burden on Patrick to reconcile _his_ code with yours when the time comes, hehehe

**Comment by joeweiss** [comment]
@ehpersonal38 Cool. PR in.

**Comment by mcguirepr89** [comment]
Howdy, @joeweiss!! I merged the branch that was created from the PR for this into `main` just now -- thanks again for the awesome refactoring!
