### ISSUE TITLE
javascript error: Uncaught ReferenceError: dialogPolyfill is not defined  

### ISSUE THREAD

**Issue by idcrook** [mcguirepr89/BirdNET-Pi#409]
**Describe the bug**

`dialogPolyfill` is missing from Javascript

**To Reproduce**
1. Go to Overview, Today's Detections, Species Stats subpages
4. See errors in javascript console

```
views.php?view=Today%27s+Detections:83 Uncaught ReferenceError: dialogPolyfill is not defined
    at views.php?view=Today%27s+Detections:83:3
    at views.php?view=Overview:82
```

**From browser/BirdNetPi**

- UA: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- `git show HEAD`
```
commit 39a0ba56972c944fbbd3b8fbbeaf7a5f3376bcc3 (HEAD -> main, origin/main, origin/HEAD)
Author: mcguirepr89 <xxx.com>
Date:   Mon Jun 27 10:49:54 2022 -0400

    unfortunately, lazy loading is not working on iOS
```

**Expected behavior**

Expect to have any needed javascript libraries gracefully found. Not sure if any required functionality is missing.

```
$ git grep dialogPolyfill
scripts/overview.php:  dialogPolyfill.registerDialog(dialog);
scripts/stats.php:dialogPolyfill.registerDialog(dialog);
scripts/todays_detections.php:  dialogPolyfill.registerDialog(dialog);
```

**Comment by ehpersonal38** [comment]
Thanks for bringing this to my attention. Would you be able to confirm if the dialogs are working or not on your Mac? They appear whenever you click a bird image (if you have Flickr images enabled)

You should see something like this pop up if they're working:
![chrome_SiY4lHPnxT](https://user-images.githubusercontent.com/103586016/176019732-66531405-6bbb-40ce-bfa5-df86663a8ba0.png)
.
