### ISSUE TITLE
Whoops, unable to update? 

### ISSUE THREAD

**Issue by b0rnwr0ng** [mcguirepr89/BirdNET-Pi#416]
After switching to test mode and then runningnupdate to stable, nothing working at this point and unable to run the update again.

It seems update_birdnet.sh is empty now, too.

Can't locate the thread even for the test-- sorry I'm a mess lol

**Comment by ehpersonal38** [comment]
Sorry to hear this - can you run `ls -lh $HOME/BirdNET-Pi` and paste the output?

**Comment by b0rnwr0ng** [comment]
No worries at all.  Output below


 ls -lh $HOME/BirdNET-Pi
total 62M
-rw-rw-r-- 1 pi pi   73 Jun 30 08:38 analyzing_now.txt
-rw-rw-r-- 1 pi pi    0 Jun 30 08:55 apprise.txt
-rw-rw-r-- 1 pi pi 1.8M Jun 30 09:02 BirdDB.txt
drwxrwxr-x 7 pi pi 4.0K Apr 22 22:32 birdnet
-rw-rw-r-- 1 pi pi 6.1K Jun 30 08:55 birdnet.conf
-rw-rw-r-- 1 pi pi 6.3K Jun 30 08:47 birdnet.conf-defaults
-rw-rw-r-- 1 pi pi    0 Apr 22 22:34 exclude_species_list.txt
-rw-rw-r-- 1 pi pi  914 Jun 30 09:01 firstrun.ini
drwxrwxr-x 4 pi pi 4.0K Jun 30 08:47 homepage
-rw-rw-r-- 1 pi pi 1.2M Jun 30 00:05 HUMAN.txt
-rw-rw-r-- 1 pi pi  173 May 11 13:12 IdentifiedSoFar.txt
-rw-rw-r-- 1 pi pi    0 Apr 22 22:34 include_species_list.txt
-rw-rw-r-- 1 pi pi    0 Jun 30 08:47 __init__.py
-rw-rw-r-- 1 pi pi  83K Jun 30 08:47 LICENSE
drwxrwxr-x 2 pi pi 4.0K Jun 30 08:47 model
-rwxrwxr-x 1 pi pi  724 Jun 30 08:47 newinstaller.sh
-rw-rw-r-- 1 pi pi 8.3K Jun 30 08:47 README.md
-rw-rw-r-- 1 pi pi  190 Jun 30 08:47 requirements.txt
drwxrwxr-x 4 pi pi 4.0K Jun 30 09:03 scripts
drwxrwxr-x 2 pi pi 4.0K Jun 30 08:47 templates
drwxrwxr-x 2 pi pi 4.0K Jun 30 08:47 tests
-rw-rw-r-- 1 pi pi  59M Jun 30 08:47 tflite_runtime-2.6.0-cp39-none-linux_aarch64.whl
-rw-rw-r-- 1 pi pi 2.0K Jun 30 08:47 version.md

**Comment by ehpersonal38** [comment]
Everything looks mostly normal there - so "scripts/update_birdnet.sh" is completely blank?

Could we see a `ls -lh $HOME/BirdNET-Pi/scripts` ?

**Comment by b0rnwr0ng** [comment]
Correct.

**Comment by ehpersonal38** [comment]
Okay, maybe you can try:

```
cd $HOME/BirdNET-Pi
git checkout -f
git pull
update_birdnet.sh
restart_services.sh
```

**Comment by ehpersonal38** [comment]
Glad to hear this was resolved, sorry for breaking it with the test branch. Still don't know why that would've happened. Closing now!

**Comment by ehpersonal38** [comment]
@b0rnwr0ng I just discovered an issue with the test branch that will have persisted to your installation even after switching to main. If you could run this command it should sort this out:

```
echo "" | sudo tee -a /etc/crontab
sudo service cron restart
```

@mcguirepr89 You may be affected too. I think me editing the weekly_report.cron template from Windows caused /etc/crontab to be without a newline at the end.

**Comment by b0rnwr0ng** [comment]
Ran it, thank you!
________________________________
