### ISSUE TITLE
Only works with initial PI user

### ISSUE THREAD

**Issue by garbled1** [mcguirepr89/BirdNET-Pi#419]
### PLEASE READ THE DOCUMENTATION BEFORE SUBMITTING AN ISSUE
**Describe the bug**

This was not obvious during installation, but this only works with the initial pi user.  I had created a new user to run the software under, and when I tried to launch it, it exploded spectacularly.  It was only obvious when I attempted to upgrade, and found:

```
USER=$(awk -F: '/1000/ {print $1}' /etc/passwd)
HOME=$(awk -F: '/1000/ {print $6}' /etc/passwd)
```
in the upgrade script.

**To Reproduce**
Install birdpi as non-initial PI user.

**Expected behavior**
Documentation should have stopped me, or the script should refuse to install if uid != 1000

**Screenshots**

**Additional context**

**Comment by mcguirepr89** [comment]
Hello, @garbled1 

Please follow the installation guide and let me know if you have any issues. If following the installation guide does not result in a successful installation, I will reopen this issue to look into it further, though from what I can tell now, the guide was not referenced during installatoin.

My best,
Patrick
