### ISSUE TITLE
No Detections For Today

### ISSUE THREAD

**Issue by lloydbayley** [mcguirepr89/BirdNET-Pi#425]
G'day!

A small weirdness, the main screen shows No Detections For Today, yet there are 118 detections right next to it.
There's a conundrum for you! :)

**Comment by mcguirepr89** [comment]
Go to "Tools" > "Services"  and restart the "Chart Viewer" and that should fix things for you

**Comment by lloydbayley** [comment]
Well how about that! Simple when you know how!
Thanks Patrick! :)
