### ISSUE TITLE
Install broken 

### ISSUE THREAD

**Issue by GrahamGIGA** [mcguirepr89/BirdNET-Pi#480]
### PLEASE READ THE DOCUMENTATION BEFORE SUBMITTING AN ISSUE
**Describe the bug**
Installation proceeded till this point:

Successfully built pyrsistent psutil
Installing collected packages: traitlets, six, pyrsistent, attrs, wcwidth, tornado, pyzmq, python-dateutil, pycparser, pure-eval, ptyprocess, parso, nest-asyncio, jupyter-core, jsonschema, fastjsonschema, executing, entrypoints, asttokens, webencodings, stack-data, soupsieve, setuptools, pyparsing, pygments, prompt-toolkit, pickleshare, pexpect, nbformat, matplotlib-inline, MarkupSafe, jupyter-client, jedi, decorator, cffi, backcall, tinycss2, psutil, pandocfilters, packaging, nbclient, mistune, jupyterlab-pygments, jinja2, ipython, defusedxml, debugpy, bleach, beautifulsoup4, argon2-cffi-bindings, terminado, Send2Trash, prometheus-client, nbconvert, ipython-genutils, ipykernel, argon2-cffi, notebook, zipp, widgetsnbextension, urllib3, tzdata, smmap, pytz, numpy, llvmlite, jupyterlab-widgets, idna, charset-normalizer, certifi, toolz, tomli, threadpoolctl, scipy, requests, pytz-deprecation-shim, py, pluggy, pillow, pandas, oauthlib, numba, kiwisolver, joblib, ipywidgets, iniconfig, importlib-metadata, gitdb, fonttools, cycler, commonmark, appdirs, watchdog, validators, tzlocal, typing-extensions, toml, tenacity, soundfile, semver, scikit-learn, rich, resampy, requests-oauthlib, PyYAML, pytest, pympler, pydeck, pyarrow, protobuf, pooch, matplotlib, markdown, gitpython, click, cachetools, blinker, audioread, altair, wheel, tflite-runtime, streamlit, seaborn, pytest-mock, plotly, pip, paho-mqtt, librosa, colorama, apprise
  Attempting uninstall: setuptools
    Found existing installation: setuptools 44.1.1
    Uninstalling setuptools-44.1.1:
      Successfully uninstalled setuptools-44.1.1
client_loop: send disconnect: Broken pipe

**To Reproduce**
Didn't attempt a reinstall yet

**Expected behavior**

**Screenshots**

**Additional context**
Rebooting the Pi gave a web server interface, but attempting to save basic settings locks up the web interface.  Settings are not saved.

**Comment by mcguirepr89** [comment]
The last line of your output implies that your SSH connection to the BirdNET-Pi dropped during the installation. I'm sorry to say you'll need to attempt another installation and hope that the network does not drop the SSH session :/

Please reopen this issue if the next installation fails with something other than:
```
client_loop: send disconnect: Broken pipe
```

My very best regards,
Patrick
