### ISSUE TITLE
Multiple BirdNet-Pi's on the same network

### ISSUE THREAD

**Issue by paulhurdubelea** [mcguirepr89/BirdNET-Pi#486]
Hello! I tried to connect 3 Raspberry's on the same network. The first one is working properly, but the 2nd and 3rd one don't process the audio recieved. I know that the audio is recieved because the spectogram is displaying the sounds properly.

For the first RPI I kept the same hostname (the default one), but for the other 2 I changed the hostname in order to acces them from the same network, so I think that might be the problem, but I don't know how to solve it. Also in the Tools>System Info tab, 2 processes are off.
![Birdnet process status](https://user-images.githubusercontent.com/108002509/183861744-ffcdffb2-ccc6-4c29-a7c2-4a43dd42d009.png)

**Comment by mcguirepr89** [comment]
Hi, @paulhurdubelea -- thanks for installing BirdNET-Pi.

>but for the other 2 I changed the hostname in order to access them from the same network . . .

Did you do this in [step 8 of the installation instructions](https://github.com/mcguirepr89/BirdNET-Pi/wiki/Installation-Guide#9), or post-install? (Hint, only the former is supported.)

If you did change the hostname during step 8 of the installation guide, could you please provide some log output from the two installations that are not working? To start, just let me know what you see in the "View Logs" page for each installation and we'll take things from there.

My very best regards,
Patrick

**Comment by paulhurdubelea** [comment]
Hi @mcguirepr89 and thank you for answering! I changed the hostname during the installation, not post-install. I will attach photos with the log output.

![image](https://user-images.githubusercontent.com/108002509/183888423-db608e22-5d61-459a-9df8-92a00d83728a.png)
For raspberry nr. 2

![image](https://user-images.githubusercontent.com/108002509/183888333-b1268eea-15c9-4e6e-bf78-f63861ba8e4b.png)
For raspberry nr. 3

**Comment by mcguirepr89** [comment]
:dang:

Those both look like there were issues during the installation for the python virtual environment -- one cannot find the `librosa` module and the other cannot locate `tzlocal`.

On both of those devices, try issuing the following:
- ```
  uninstall.sh && cd ~/BirdNET-Pi && rm -drf ./birdnet && ./scripts/install_birdnet.sh
  ```

That command should uninstall what was successfully installed, remove the python virtual environment completely, and re-initiate the installation.

I'm hopeful that will clear up the issues with the python virtual environment that I suspect are the root of the trouble here.

Please let me know how the installations respond to that command :crossed_fingers:

**Comment by paulhurdubelea** [comment]
Thank you for the suggestions and I will let you know if it works.

**Comment by paulhurdubelea** [comment]
Ok so I tried using the commands and I got into some pretty nasty studd, other processes stopped working. 

I reinstalled the OS and used the default hostname, proceeded with the installation guide and after all of this I changed the hostname in the terminal. All the issues were solved and the BirdNet-Pi is working properly! 

Thank you for your help!

**Comment by mcguirepr89** [comment]
Very glad you're up and running. I will close this issue now.

My very best regards as always,
Patrick
