### ISSUE TITLE
BirdNET-Pi log looks like it is a day behind

### ISSUE THREAD

**Issue by trophyguy** [mcguirepr89/BirdNET-Pi#575]
This morning (Sunday) I was looking at my log and it's Sunday morning with the correct time listed on the log but looks like everything in my log is being analysed as Saturday?

![Untitled](https://user-images.githubusercontent.com/24763609/192139832-0c42fea1-a380-41df-82c3-a6d14767a396.jpg)

I haven't rebooted in a few days. Last time was when the PI went unresponsive. Could this be related to another issue I noticed Saturday also. In the screenshot, the chart at the top of the page shows today's top 10 detections and has a timestamp of 18:16. The most recent detection shown below this has a timestamp of 09:12 for Saturday. The "currently analysing" graph on the main page has been slowly analysing the sounds from the previous day also.

![Screenshot_20220924-181837](https://user-images.githubusercontent.com/24763609/192140008-2c375d68-0a0f-49d6-b98c-b0a852ee0622.png)

![Screenshot_20220924-181842](https://user-images.githubusercontent.com/24763609/192140005-cf2814bc-40a0-4b8a-bea6-9de8df481b17.png)

I was looking in System Info to see if it shows the current date and time and don't see that in there. Just the last reboot and uptime.

Thanks,
Tony

**Comment by lloydbayley** [comment]
Just had a look at your site and it seems that everything has caught up now. Is it still going ok? Was it just a glitch in the matrix? :)

**Comment by trophyguy** [comment]
Yes, all is well now. I kept an eye on the log and it took a few hours but it analyzed and processed everything from the previous day and then continued on to the next days things. An odd hiccup but all is well now.

**Comment by lloydbayley** [comment]
Glad to hear it. It's happened to me before. It seems your message was overlooked for some time. I usually try to help where I can sooner but there's quite a few issues that I'm not sure why they are still open. Anyway, all is well for you now and that's what matters!

[ Mods: Could someone have a look at this and close some of these stale issues? ]
