### ISSUE TITLE
Date of "Detected species" with max confidence score

### ISSUE THREAD

**Issue by DD4WH** [mcguirepr89/BirdNET-Pi#58]
In the "Databse view" there is a table with species sorted by maximum confidence scores, called "Detected species"

It seems the date for those events with max confidence score is not properly retrieved from the data base.
In my case, it uses a date/time where there are no extracted recordings of that particular species.

Hmm, the more I investigate this, I get the impression, it is a feature of the automatic deleting of files!
I did not know that the extracted files get deleted too! I do not think this is useful, but will think about this.

**Comment by mcguirepr89** [comment]
Hi @DD4WH I wanted to follow up with you to see if you were able to check on the extraction service to see if an issue with it explains the missing extractions.

My best

**Comment by mcguirepr89** [comment]
Closing without a response
