### ISSUE TITLE
BirdNET Analysis client won't start & latitude not set

### ISSUE THREAD

**Issue by tdelattre** [mcguirepr89/BirdNET-Pi#594]
Hi all, 
need some help please :-)
I can't get the BirdNET Analysis client service to start. It stays inactive. 
When I click on "restart" for this service, I get an exit & failure for birdnet_analysis.sh
Main PID:4021 (code=exited, status =1/FAILURE)

Edit: 
sudo systemctl restart birdnet_analysis.service 
works if launched directly in the system console

But after that I still don't get any detection. In the log is see repeated errors :
-IndexError: list index out of range
LATITUDE not set, exiting 1

The thing is I don't see where I can set latitude and longitude. Maybe it is in Tools/Settings but I can't access this menu (although I can access the rest of the tools menus). The login prompt pops up specifically for this menu even if I'm already logged in, and no login or password seems to do the trick.

New edit: I fond a way to add manually Lat & long in the BirdNET.conf file. After that everything works, and I can even access the Settings page.

**Comment by blite** [comment]
I had this problem as well, couldn't do anything till I set lat long in .conf
