### ISSUE TITLE
Regular daily freezing of services

### ISSUE THREAD

**Issue by cornerkilling** [mcguirepr89/BirdNET-Pi#595]
### PLEASE READ THE DOCUMENTATION BEFORE SUBMITTING AN ISSUE
**Describe the bug**

Analyzing stops after several hours of running. This issue has happened several days in a row. A reboot or restarting all services prompts the analyzer to starting working through the backlog of recordings. 

**To Reproduce**
Issue happens after several hours. No specific actions cause it.

**Expected behavior**

**Screenshots**
![Screenshot 2022-10-07 092507](https://user-images.githubusercontent.com/97748126/194567926-f2c49b5f-1f8e-428b-a78c-ce116cb4aa28.png)

**Additional context**
Started recently using Apprise to notify Home Assistant via mqtt. No other config changes have been made recently. No updates are pending.

**Comment by lloydbayley** [comment]
I know it's a simple thing and not meaning to be rude at all, but have you checked on your available disk space? It's happened to me before when it's gone awry and used up all the disk space with unprocessed recordings. I didn't have mine set to purge and it would sometimes do this.

**Comment by cornerkilling** [comment]
Not a bad idea, I hadn't checked. I have an old 120GB ssd plugged in for storage and didn't think it would fill up any time soon. It looks fine right now.
![image](https://user-images.githubusercontent.com/97748126/194585766-69a970a4-de58-40df-8453-1d553bbf57f8.png)

**Comment by jds3d** [comment]
I have also recently had this issue. But mine isn't lasting several hours,
it just processed a couple more files and then dies. Still looking into
clues.

**Comment by ehpersonal38** [comment]
Can you try paging through this command and see what happened the moment the analysis stopped? Maybe an error message?
```
journalctl --no-hostname -ubirdnet_analysis -ubirdnet_server -uextraction -ubirdnet_recording
```

**Comment by cornerkilling** [comment]
Here is the output from yesterday when I restarted services and rebooted. 
>
Oct 06 12:16:33 birdnet_analysis.sh[1633319]: RECORDING_LENGTH set to 30
Oct 06 12:16:33 birdnet_analysis.sh[1633319]: /home/pi/BirdNET-Pi/birdnet/bin/p>
Oct 06 12:16:33 python3[1633318]: ANALYZING AUDIO... DONE! Time 3.1 SECONDS
Oct 06 12:16:33 python3[1633318]: WRITING RESULTS TO /home/pi/BirdSongs/October>
Oct 06 12:16:33 python3[1633318]: READING AUDIO DATA... DONE! READ 10 CHUNKS.
Oct 06 12:16:33 python3[1633318]: Date-time: 2022-10-06 12:03:33
Oct 06 12:16:37 birdnet_analysis.sh[1633730]: 0.0;3.0-('Helmitheros vermivorum_>
Oct 06 12:16:37 birdnet_analysis.sh[1633730]: 3.0;6.0-('Chaetura pelagica_Chimn>
Oct 06 12:16:37 birdnet_analysis.sh[1633730]: 6.0;9.0-('Chaetura pelagica_Chimn>
Oct 06 12:16:37 birdnet_analysis.sh[1633730]: 9.0;12.0-('Chaetura pelagica_Chim>
Oct 06 12:16:37 birdnet_analysis.sh[1633730]: 12.0;15.0-('Chaetura pelagica_Chi>
Oct 06 12:16:37 birdnet_analysis.sh[1633730]: 15.0;18.0-('Chaetura pelagica_Chi>
Oct 06 12:16:37 birdnet_analysis.sh[1633730]: 18.0;21.0-('Chaetura pelagica_Chi>
Oct 06 12:16:37 birdnet_analysis.sh[1633730]: 21.0;24.0-('Chaetura pelagica_Chi>
Oct 06 12:16:37 birdnet_analysis.sh[1633730]: 24.0;27.0-('Chaetura pelagica_Chi>
Oct 06 12:16:37 birdnet_analysis.sh[1633730]: 27.0;30.0-('Chaetura pelagica_Chi>
Oct 06 12:16:37 birdnet_analysis.sh[1633319]: RECORDING_LENGTH set to 30
Oct 06 12:16:37 birdnet_analysis.sh[1633319]: /home/pi/BirdNET-Pi/birdnet/bin/p>
Oct 06 12:16:37 python3[1633318]: ANALYZING AUDIO... DONE! Time 3.0 SECONDS
Oct 06 12:16:37 python3[1633318]: WRITING RESULTS TO /home/pi/BirdSongs/October>
Oct 06 12:16:37 python3[1633318]: READING AUDIO DATA... DONE! READ 10 CHUNKS.
Oct 06 12:16:37 python3[1633318]: Date-time: 2022-10-06 12:03:59
Oct 06 12:16:40 birdnet_analysis.sh[1633764]: 0.0;3.0-('Chaetura pelagica_Chimn>
Oct 06 12:16:40 birdnet_analysis.sh[1633764]: 3.0;6.0-('Chaetura pelagica_Chimn>
Oct 06 12:16:40 birdnet_analysis.sh[1633764]: 6.0;9.0-('Chaetura pelagica_Chimn>
Oct 06 12:16:40 birdnet_analysis.sh[1633764]: 9.0;12.0-('Helmitheros vermivorum>
Oct 06 12:16:40 birdnet_analysis.sh[1633764]: 12.0;15.0-('Helmitheros vermivoru>
Oct 06 12:16:40 birdnet_analysis.sh[1633764]: 15.0;18.0-('Chaetura pelagica_Chi>
Oct 06 12:16:40 birdnet_analysis.sh[1633764]: 18.0;21.0-('Chaetura pelagica_Chi>
Oct 06 12:16:40 birdnet_analysis.sh[1633764]: 21.0;24.0-('Chaetura pelagica_Chi>
Oct 06 12:16:40 birdnet_analysis.sh[1633764]: 24.0;27.0-('Chaetura pelagica_Chi>
Oct 06 12:16:40 birdnet_analysis.sh[1633764]: 27.0;30.0-('Chaetura pelagica_Chi>
Oct 06 12:16:40 birdnet_analysis.sh[1633319]: RECORDING_LENGTH set to 30
Oct 06 12:16:40 birdnet_analysis.sh[1633319]: /home/pi/BirdNET-Pi/birdnet/bin/p>
Oct 06 12:16:40 python3[1633318]: ANALYZING AUDIO... DONE! Time 3.1 SECONDS
Oct 06 12:16:40 python3[1633318]: WRITING RESULTS TO /home/pi/BirdSongs/October>
Oct 06 12:16:41 python3[1633318]: READING AUDIO DATA... DONE! READ 10 CHUNKS.
Oct 06 12:16:41 python3[1633318]: Date-time: 2022-10-06 12:04:29
Oct 06 12:16:49 birdnet_analysis.sh[1633801]: 0.0;3.0-('Chaetura pelagica_Chimn>
Oct 06 12:16:49 birdnet_analysis.sh[1633801]: 3.0;6.0-('Chaetura pelagica_Chimn>
Oct 06 12:16:49 birdnet_analysis.sh[1633801]: 6.0;9.0-('Chaetura pelagica_Chimn>
Oct 06 12:16:49 birdnet_analysis.sh[1633801]: 9.0;12.0-('Chaetura pelagica_Chim>
Oct 06 12:16:49 birdnet_analysis.sh[1633801]: 12.0;15.0-('Chaetura pelagica_Chi>
Oct 06 12:16:49 birdnet_analysis.sh[1633801]: 15.0;18.0-('Chaetura pelagica_Chi>
Oct 06 12:16:49 birdnet_analysis.sh[1633801]: 18.0;21.0-('Chaetura pelagica_Chi>
Oct 06 12:16:49 birdnet_analysis.sh[1633801]: 21.0;24.0-('Chaetura pelagica_Chi>
Oct 06 12:16:49 birdnet_analysis.sh[1633801]: 24.0;27.0-('Chaetura pelagica_Chi>
Oct 06 12:16:49 birdnet_analysis.sh[1633801]: 27.0;30.0-('Chaetura pelagica_Chi>
Oct 06 12:16:49 birdnet_analysis.sh[1633319]: RECORDING_LENGTH set to 30
Oct 06 12:16:49 birdnet_analysis.sh[1633319]: /home/pi/BirdNET-Pi/birdnet/bin/p>
Oct 06 12:16:49 python3[1633318]: ANALYZING AUDIO... DONE! Time 3.0 SECONDS
Oct 06 12:16:49 python3[1633318]: WRITING RESULTS TO /home/pi/BirdSongs/October>
Oct 06 12:16:49 python3[1633318]: 2022-10-06;12:04:29;Chaetura pelagica;Chimney>
Oct 06 12:16:49 python3[1633318]: Soundscape POST Response Status -  201
Oct 06 12:16:49 python3[1633318]: { "timestamp": "2022-10-06T12:04:38-04:00","l>
Oct 06 12:16:49 python3[1633318]: Detection POST Response Status -  201
Oct 06 12:16:50 python3[1633318]: READING AUDIO DATA... DONE! READ 10 CHUNKS.
Oct 06 12:16:50 python3[1633318]: Date-time: 2022-10-06 12:04:59
Oct 06 12:16:53 birdnet_analysis.sh[1633867]: 0.0;3.0-('Chaetura pelagica_Chimn>
Oct 06 12:16:53 birdnet_analysis.sh[1633867]: 3.0;6.0-('Chaetura pelagica_Chimn>
Oct 06 12:16:53 birdnet_analysis.sh[1633867]: 6.0;9.0-('Chaetura pelagica_Chimn>
Oct 06 12:16:53 birdnet_analysis.sh[1633867]: 9.0;12.0-('Megaceryle alcyon_Belt>
Oct 06 12:16:53 birdnet_analysis.sh[1633867]: 12.0;15.0-('Helmitheros vermivoru>
Oct 06 12:16:53 birdnet_analysis.sh[1633867]: 15.0;18.0-('Helmitheros vermivoru>
Oct 06 12:16:53 birdnet_analysis.sh[1633867]: 18.0;21.0-('Chaetura pelagica_Chi>
Oct 06 12:16:53 birdnet_analysis.sh[1633867]: 21.0;24.0-('Helmitheros vermivoru>
Oct 06 12:16:53 birdnet_analysis.sh[1633867]: 24.0;27.0-('Chaetura pelagica_Chi>
Oct 06 12:16:53 birdnet_analysis.sh[1633867]: 27.0;30.0-('Chaetura pelagica_Chi>
Oct 06 12:16:53 birdnet_analysis.sh[1633319]: RECORDING_LENGTH set to 30
Oct 06 13:55:03 birdnet_recording.sh[1074285]: Aborted by signal Terminated...
Oct 06 13:55:04 python3[1633318]: ANALYZING AUDIO...
Oct 06 13:55:03 systemd[1]: Stopping BirdNET Analysis...
Oct 06 13:55:03 systemd[1]: Stopping BirdNET Recording...
Oct 06 13:55:03 systemd[1]: Stopping BirdNET BirdSound Extraction...
Oct 06 13:55:03 systemd[1]: extraction.service: Succeeded.
Oct 06 13:55:03 systemd[1]: Stopped BirdNET BirdSound Extraction.
Oct 06 13:55:03 systemd[1]: extraction.service: Consumed 2h 21min 17.337s CPU t>
Oct 06 13:55:03 systemd[1]: birdnet_analysis.service: Succeeded.
Oct 06 13:55:03 systemd[1]: Stopped BirdNET Analysis.
Oct 06 13:55:03 systemd[1]: birdnet_analysis.service: Consumed 3min 33.785s CPU>
Oct 06 13:55:03 systemd[1]: birdnet_recording.service: Succeeded.
Oct 06 13:55:03 systemd[1]: Stopped BirdNET Recording.
Oct 06 13:55:03 systemd[1]: birdnet_recording.service: Consumed 8min 7.669s CPU>
Oct 06 13:55:03 systemd[1]: Stopping BirdNET Analysis Server...
Oct 06 13:55:03 systemd[1]: birdnet_server.service: Succeeded.
Oct 06 13:55:03 systemd[1]: Stopped BirdNET Analysis Server.
Oct 06 13:55:03 systemd[1]: birdnet_server.service: Consumed 1min 1.220s CPU ti>
-- Boot 7e6f14de5b1e4de4ae4d894cc316fda9 --
Oct 06 13:55:14 systemd[1]: Started BirdNET Recording.
Oct 06 13:55:14 systemd[1]: Started BirdNET Analysis Server.
Oct 06 13:55:14 systemd[1]: Started BirdNET Analysis.
Oct 06 13:55:14 systemd[1]: Started BirdNET BirdSound Extraction.
Oct 06 13:55:14 birdnet_recording.sh[396]: + source /etc/birdnet/birdnet.conf
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ LATITUDE=40.1149
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ LONGITUDE=-82.9054
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ BIRDWEATHER_ID=Yjea52eLEQM2SooQf8>
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ CADDY_PWD=IgfSJi2009
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ ICE_PWD=birdnetpi
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ BIRDNETPI_URL=https://birdfish.dd>
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ RTSP_STREAM=
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ APPRISE_NOTIFICATION_TITLE=
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ APPRISE_NOTIFICATION_BODY='{"Comm>
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ APPRISE_NOTIFY_EACH_DETECTION=1
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ RECS_DIR=/home/pi/BirdSongs
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ REC_CARD=default
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ PROCESSED=/home/pi/BirdSongs/Proc>
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ EXTRACTED=/home/pi/BirdSongs/Extr>
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ OVERLAP=0.0
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ CONFIDENCE=0.7
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ SENSITIVITY=1.25
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ CHANNELS=2
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ FULL_DISK=purge
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ PRIVACY_THRESHOLD=2
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ RECORDING_LENGTH=30
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ EXTRACTION_LENGTH=15
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ AUDIOFMT=mp3
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ LAST_RUN=
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ THIS_RUN=
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ IDFILE=/home/pi/BirdNET-Pi/Identi>
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ APPRISE_NOTIFY_NEW_SPECIES=0
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ DATABASE_LANG=en
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ FLICKR_API_KEY=f63b718dff9c83eade>
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ FLICKR_FILTER_EMAIL=
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ APPRISE_NOTIFY_NEW_SPECIES_EACH_D>
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ SILENCE_UPDATE_INDICATOR=0
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ APPRISE_WEEKLY_REPORT=0
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ APPRISE_MINIMUM_SECONDS_BETWEEN_N>
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ FREQSHIFT_TOOL=sox
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ FREQSHIFT_HI=6000
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ FREQSHIFT_LO=3000
Oct 06 13:55:15 birdnet_recording.sh[396]: ++ FREQSHIFT_PITCH=-1500
Oct 06 13:55:15 birdnet_recording.sh[396]: + '[' -z 30 ']'
Oct 06 13:55:15 birdnet_recording.sh[396]: + '[' '!' -z ']'
Oct 06 13:55:15 birdnet_recording.sh[396]: + pulseaudio --check
Oct 06 13:55:15 birdnet_recording.sh[445]: E: [pulseaudio] core-util.c: Failed >
Oct 06 13:55:15 birdnet_recording.sh[396]: + pulseaudio --start
Oct 06 13:55:15 birdnet_recording.sh[543]: E: [autospawn] core-util.c: Failed t>
Oct 06 13:55:15 birdnet_recording.sh[543]: W: [autospawn] lock-autospawn.c: Can>
Oct 06 13:55:15 birdnet_recording.sh[543]: E: [pulseaudio] main.c: Failed to ac>
Oct 06 13:55:15 birdnet_recording.sh[396]: + pgrep arecord
Oct 06 13:55:15 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:15 birdnet_recording.sh[564]: ++ netstat -tulpn
Oct 06 13:55:15 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:16 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:16 birdnet_recording.sh[607]: ++ netstat -tulpn
Oct 06 13:55:16 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:17 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:17 birdnet_recording.sh[623]: ++ netstat -tulpn
Oct 06 13:55:17 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:18 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:18 birdnet_recording.sh[634]: ++ netstat -tulpn
Oct 06 13:55:18 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:19 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:19 birdnet_recording.sh[644]: ++ netstat -tulpn
Oct 06 13:55:19 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:20 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:20 birdnet_recording.sh[655]: ++ netstat -tulpn
Oct 06 13:55:20 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:21 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:21 birdnet_recording.sh[664]: ++ netstat -tulpn
Oct 06 13:55:21 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:22 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:22 birdnet_recording.sh[711]: ++ netstat -tulpn
Oct 06 13:55:22 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:23 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:23 birdnet_recording.sh[719]: ++ netstat -tulpn
Oct 06 13:55:23 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:24 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:24 birdnet_recording.sh[727]: ++ netstat -tulpn
Oct 06 13:55:24 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:25 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:25 birdnet_recording.sh[755]: ++ netstat -tulpn
Oct 06 13:55:25 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:42 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:42 birdnet_recording.sh[840]: ++ netstat -tulpn
Oct 06 13:55:42 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:43 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:43 birdnet_recording.sh[855]: ++ netstat -tulpn
Oct 06 13:55:43 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:44 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:44 birdnet_recording.sh[870]: ++ netstat -tulpn
Oct 06 13:55:44 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:45 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:45 birdnet_recording.sh[895]: ++ netstat -tulpn
Oct 06 13:55:45 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:46 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:46 birdnet_recording.sh[903]: ++ netstat -tulpn
Oct 06 13:55:46 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:47 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:47 birdnet_recording.sh[916]: ++ netstat -tulpn
Oct 06 13:55:47 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:47 python3[397]: INFO: Created TensorFlow Lite XNNPACK delegate fo>
Oct 06 13:55:47 python3[397]: INFO: Created TensorFlow Lite delegate for select>
Oct 06 13:55:47 python3[397]: INFO: TfLiteFlexDelegate delegate: 1 nodes delega>
Oct 06 13:55:48 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:48 birdnet_recording.sh[985]: ++ netstat -tulpn
Oct 06 13:55:48 birdnet_recording.sh[986]: tcp        0      0 127.0.0.1:5050  >
Oct 06 13:55:48 birdnet_recording.sh[396]: + '[' -z default ']'
Oct 06 13:55:48 birdnet_recording.sh[396]: + arecord -f S16_LE -c2 -r48000 -t w>
Oct 06 13:55:48 birdnet_analysis.sh[398]: Files loaded
Oct 06 13:55:49 birdnet_analysis.sh[398]: RECORDING_LENGTH set to 30
Oct 06 13:55:49 birdnet_analysis.sh[398]: /home/pi/BirdNET-Pi/birdnet/bin/pytho>
Oct 06 13:55:50 python3[397]: LOADING TF LITE MODEL... DONE!
Oct 06 13:55:50 python3[397]: READING AUDIO DATA... DONE! READ 0 CHUNKS.
Oct 06 13:55:50 python3[397]: Date-time: 2022-10-06 12:15:46
Oct 06 13:55:50 birdnet_recording.sh[988]: Recording WAVE '/home/pi/BirdSongs/%>
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:00:29.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:00:59.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:01:29.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:01:59.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:02:29.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:02:59.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:03:33.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:03:59.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:04:29.wav.csv
Oct 06 13:55:51 env[1067]: Line = 9.0;12.0;Chaetura pelagica;Chimney Swift;0.74>
Oct 06 13:55:51 env[1067]: NEWFILE=Chimney_Swift-74-2022-10-06-birdnet-12:04:29>
Oct 06 13:55:52 env[1067]: Line = 2022-10-06-birdnet-12:04:59.wav.csv
Oct 07 00:00:02 env[238780]: Removing old directories
Oct 07 09:25:21 systemd[1]: Stopping BirdNET Analysis...
Oct 07 09:25:21 systemd[1]: birdnet_analysis.service: Succeeded.
Oct 07 09:25:21 systemd[1]: Stopped BirdNET Analysis.
Oct 07 09:25:21 systemd[1]: Stopping BirdNET Analysis Server...
Oct 07 09:25:21 python3[397]: ANALYZING AUDIO...
Oct 07 09:25:21 systemd[1]: birdnet_server.service: Succeeded.
Oct 07 09:25:21 systemd[1]: Stopped BirdNET Analysis Server.
Oct 07 09:25:21 systemd[1]: birdnet_server.service: Consumed 5.274s CPU time.
Oct 07 09:25:21 systemd[1]: Stopping BirdNET Recording...
Oct 07 09:25:21 birdnet_recording.sh[988]: Aborted by signal Terminated...
Oct 07 09:25:21 systemd[1]: birdnet_recording.service: Succeeded.
Oct 06 13:55:45 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:46 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:46 birdnet_recording.sh[903]: ++ netstat -tulpn
Oct 06 13:55:46 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:47 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:47 birdnet_recording.sh[916]: ++ netstat -tulpn
Oct 06 13:55:47 birdnet_recording.sh[396]: + sleep 1
Oct 06 13:55:47 python3[397]: INFO: Created TensorFlow Lite XNNPACK delegate fo>
Oct 06 13:55:47 python3[397]: INFO: Created TensorFlow Lite delegate for select>
Oct 06 13:55:47 python3[397]: INFO: TfLiteFlexDelegate delegate: 1 nodes delega>
Oct 06 13:55:48 birdnet_recording.sh[396]: + grep 5050 /dev/fd/63
Oct 06 13:55:48 birdnet_recording.sh[985]: ++ netstat -tulpn
Oct 06 13:55:48 birdnet_recording.sh[986]: tcp        0      0 127.0.0.1:5050  >
Oct 06 13:55:48 birdnet_recording.sh[396]: + '[' -z default ']'
Oct 06 13:55:48 birdnet_recording.sh[396]: + arecord -f S16_LE -c2 -r48000 -t w>
Oct 06 13:55:48 birdnet_analysis.sh[398]: Files loaded
Oct 06 13:55:49 birdnet_analysis.sh[398]: RECORDING_LENGTH set to 30
Oct 06 13:55:49 birdnet_analysis.sh[398]: /home/pi/BirdNET-Pi/birdnet/bin/pytho>
Oct 06 13:55:50 python3[397]: LOADING TF LITE MODEL... DONE!
Oct 06 13:55:50 python3[397]: READING AUDIO DATA... DONE! READ 0 CHUNKS.
Oct 06 13:55:50 python3[397]: Date-time: 2022-10-06 12:15:46
Oct 06 13:55:50 birdnet_recording.sh[988]: Recording WAVE '/home/pi/BirdSongs/%>
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:00:29.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:00:59.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:01:29.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:01:59.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:02:29.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:02:59.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:03:33.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:03:59.wav.csv
Oct 06 13:55:51 env[1067]: Line = 2022-10-06-birdnet-12:04:29.wav.csv
Oct 06 13:55:51 env[1067]: Line = 9.0;12.0;Chaetura pelagica;Chimney Swift;0.74>
Oct 06 13:55:51 env[1067]: NEWFILE=Chimney_Swift-74-2022-10-06-birdnet-12:04:29>
Oct 06 13:55:52 env[1067]: Line = 2022-10-06-birdnet-12:04:59.wav.csv
Oct 07 00:00:02 env[238780]: Removing old directories

**Comment by ehpersonal38** [comment]
```
Oct 06 13:55:15 birdnet_recording.sh[445]: E: [pulseaudio] core-util.c: Failed >
Oct 06 13:55:15 birdnet_recording.sh[396]: + pulseaudio --start
Oct 06 13:55:15 birdnet_recording.sh[543]: E: [autospawn] core-util.c: Failed t>
Oct 06 13:55:15 birdnet_recording.sh[543]: W: [autospawn] lock-autospawn.c: Can>
Oct 06 13:55:15 birdnet_recording.sh[543]: E: [pulseaudio] main.c: Failed to ac>
```

These lines stand out to me as relevant. Can you paste the full lines though? It cuts off halfway through

**Comment by cornerkilling** [comment]
Oct 06 13:55:15 birdnet_recording.sh[445]: E: [pulseaudio] core-util.c: Failed to create secure directory (/run/user/1000/pulse): No such file or directory
Oct 06 13:55:15 birdnet_recording.sh[396]: + pulseaudio --start
Oct 06 13:55:15 birdnet_recording.sh[543]: E: [autospawn] core-util.c: Failed to create secure directory (/run/user/1000/pulse): No such file or directory
Oct 06 13:55:15 birdnet_recording.sh[543]: W: [autospawn] lock-autospawn.c: Cannot access autospawn lock.
Oct 06 13:55:15 birdnet_recording.sh[543]: E: [pulseaudio] main.c: Failed to acquire autospawn lock

**Comment by ehpersonal38** [comment]
Thanks for that - I edited my comment above with something to try

**Comment by cornerkilling** [comment]
Thanks, I gave that a try and will let it run for a bit.

**Comment by matthew73210** [comment]
@cornerkilling this may help in the futur when debugging but use [pastebin](https://pastebin.com/) when posting long logs.
Out of curiosity, what platform are you using, I may have missed it?

**Comment by mcguirepr89** [comment]
@owai1980 Did you follow the installation instructions for the RPi3B? (Did you add swap space and increase the recording length)?

Have you tried the solution yet, or is this just to add to a comment to the issue before trying the solution?

**Comment by jds3d** [comment]
I wanted to add that my issue looks fixed (for now) (though it was likely a different issue) as I have an RPi4.  In case this helps anyone else, I had some orphaned folders from an old install that were very large.  I cleared them but the file system was mostly unresponsive.  I couldn't do an ls on one folder with 3000 wav files, around 6GB.  I tried update through the website to get latest version, i tried restarting core services through the website, and i tried a sudo reboot.  None of that helped, and I was going to look into whether my disk was corrupt.  But then I unplugged it and replugged it in 20s later and it started chugging away on the old files.  We'll see how long it goes.

**Comment by cornerkilling** [comment]
> ```
> Oct 06 13:55:15 birdnet_recording.sh[445]: E: [pulseaudio] core-util.c: Failed >
> Oct 06 13:55:15 birdnet_recording.sh[396]: + pulseaudio --start
> Oct 06 13:55:15 birdnet_recording.sh[543]: E: [autospawn] core-util.c: Failed t>
> Oct 06 13:55:15 birdnet_recording.sh[543]: W: [autospawn] lock-autospawn.c: Can>
> Oct 06 13:55:15 birdnet_recording.sh[543]: E: [pulseaudio] main.c: Failed to ac>
> ```
> 
> These lines look similar to another issue. Could you try this solution and see if it helps?: [#302 (comment)](https://github.com/mcguirepr89/BirdNET-Pi/issues/302#issuecomment-1172912042)

Sorry about the formatting. I'll keep that in mind for the future. I'm on the Pi4. 
I let everything run over the weekend and did not have any freezes or need to restart. This issue is solved for me. Thanks!
