### ISSUE TITLE
Update TF Model from new BirdNet Analyzer Repo

### ISSUE THREAD

**Issue by tomtom215** [mcguirepr89/BirdNET-Pi#621]
**Is your feature request related to a problem? Please describe.**

The main repo this was forked from is has a deprecation warning and the .tflite 6k Global Model has not been updated in 2 years in this repo. https://github.com/kahst/BirdNET-Lite

**Describe the solution you'd like**

To update the TFLite models in this repo from the newest BirdNet models from the new BirdNet Analyzer Repo https://github.com/kahst/BirdNET-Analyzer/tree/main/checkpoints 

**Describe alternatives you've considered**

**Additional context**

**Comment by mcguirepr89** [comment]
https://github.com/mcguirepr89/BirdNET-Pi/discussions/184
