### ISSUE TITLE
Apprise Settings Config-Web UI Mismatch

### ISSUE THREAD

**Issue by mburrough** [mcguirepr89/BirdNET-Pi#627]
I noticed my new BirdNET-Pi install would occasionally stop analyzing audio. When I checked the log, I found the error in the screenshot below. I rebooted the Pi and it went back to working, but then the same error happened again. When I looked into it, I noticed that the APPRISE_MINIMUM_SECONDS_BETWEEN_NOTIFICATIONS_PER_SPECIES value wasn't being written to the birdnet.conf file, so I added it and rebooted and haven't had the problem since.

However, I also noticed that the Web UI doesn't seem to reflect some changes I made to the APPRISE settings, even if I make the changes in the UI itself. Repro steps:
1. Go to the Settings page
2. Configure an APPRISE notification (I'm using a Discord webhook)
3. Check the APPRISE_NOTIFY_NEW_SPECIES_EACH_DAY checkbox
4. Specify a minimum time between notifications per species
5. Click the Save button
6. Leave and come back to the settings page, the new species box will be unchecked and the time box will be empty.

I'm not sure if this is one issue or two, but they seem closely related.

![image](https://user-images.githubusercontent.com/1028978/198369917-4b098690-469f-4662-92ab-8960093cc7e3.png)

**Comment by bmlbytes** [comment]
I had the same issue with it stopping detections with the exact same error. It wouldn't keep the setting for "Minimum time between notifications of the same species (sec):" set in the web GUI either. 
To resolve it on my installation, I ssh'd into the Raspberry Pi and ran 
`sudo nano ~/BirdNET-Pi/scripts/utils/notifications.py`

After that I edited line 47 to be
`APPRISE_MINIMUM_SECONDS_BETWEEN_NOTIFICATIONS_PER_SPECIES = 1800  #settings_dict.get('APPRISE_MINIMUM_SECONDS_BETWEEN_NOTIFICATIONS_PER_SPECIES')`

This basically hard codes it to 30 minutes. You could change 1800 to something else, but I wanted it at 30 minutes. 
![image](https://user-images.githubusercontent.com/1875418/198385541-818340be-3cfc-4352-a094-b52f4a0611db.png)

Not the cleanest way to do it, but it looks like it's working for me so far.
