### ISSUE TITLE
Can't connect to ethernet Pi from wifi device

### ISSUE THREAD

**Issue by Gurgeh88** [mcguirepr89/BirdNET-Pi#628]
I've recently setup BirdNET-Pi on a 3B+ and it is running ok except for a weird issue with access.

I can view my instance on other ethernet connected devices on my home network but not from our phones using wifi.

Am I missing something super obvious here or is this normal behaviour?

**Comment by ehpersonal38** [comment]
What URL are you accessing from the phones? the birdnetpi.local or direct ip?

**Comment by Gurgeh88** [comment]
> What URL are you accessing from the phones? birdnetpi.local or direct ip?

Hooray! Using the IP address worked perfectly. Thank you so much. Glad it was an easy fix.
