### ISSUE TITLE
Add optional system name to web page title

### ISSUE THREAD

**Issue by Clumpton** [mcguirepr89/BirdNET-Pi#631]
**Is your feature request related to a problem? Please describe.**
I have two systems running here (front and back gardens). In my browser both tabs just say "Birdnet-Pi" and so does the page header. I have to look at the url in the address bar to see which one is which.

**Describe the solution you'd like**
Add an optional "System Name" in the settings so that tabs & pages indicate which system you are viewing.

**Describe alternatives you've considered**
Thought of hacking the html/css myself, but that would probably not survive any updates.

**Additional context**
Being able to changing page background colour (or just toolbar colour) would be a luxury addition to helping identify the system.

**Comment by lloydbayley** [comment]
I like this idea too as I am thinking about deploying a second installation at the front of the house. Believe it or not, there are quite a few more in the trees at the front that the back mic doesn't pick up.

I'm not quite sure if it's being looked at at the moment by anyone but I can't see why it can't be done at some stage. If this isn't being looked at, I might investigate to see about it if that is ok with the others. I really don't know what the etiquette is with contributing and don't want to step on any toes.

**Comment by lloydbayley** [comment]
Right-oh! Will have a crack at it. Just was worried that someone else might have been working on it.
BTW: Ethan, I've spoken to Patrick and have said it's ok to give you my email address which will make contact easier as github doesn't allow direct messages which I think is WEIRD! With a capital WE.

**Comment by lloydbayley** [comment]
Bah, I think I'm almost there but having great strife dealing with not having special, code-breaking, characters in the name. preg_replaces abound! Still working on it.

**Comment by Clumpton** [comment]
> Bah, I think I'm almost there but having great strife dealing with not having special, code-breaking, characters in the name. preg_replaces abound! Still working on it.

Just a thought... you can propose the hostname as the default, it should be different if the user has more than one system.

**Comment by lloydbayley** [comment]
Good idea. Will give that some thought!

**Comment by ehpersonal38** [comment]
> Right-oh! Will have a crack at it. Just was worried that someone else might have been working on it. BTW: Ethan, I've spoken to Patrick and have said it's ok to give you my email address which will make contact easier as github doesn't allow direct messages which I think is WEIRD! With a capital WE.

Sure!! My email is my username at gmail . com, if you ever need to reach me for something.

**Comment by lloydbayley** [comment]
I've completed this one now, the pull request was merged into the system so it now supports a site name. I think we can close this issue now!

**Comment by lloydbayley** [comment]
Actually, don't close it yet please, I've identified a bug causing it not to show after an update. Will work on it.

**Comment by ehpersonal38** [comment]
No worries, I'm not either! Thanks for your help in getting this feature request implemented! 🐤
