### ISSUE TITLE
Feature Request: Change language of user interface

### ISSUE THREAD

**Issue by k-sartor** [mcguirepr89/BirdNET-Pi#641]
**Describe the solution you'd like**
Select a language to translate the menu of the interface

**Describe alternatives you've considered**
Add a file to read these data and each could translate the text and up into github

**Comment by lloydbayley** [comment]
I like this idea too as I am thinking about deploying a second installation at the front of the house. Believe it or not, there are quite a few more in the trees at the front that the back mic doesn't pick up.

I'm not quite sure if it's being looked at at the moment by anyone but I can't see why it can't be done at some stage. If this isn't being looked at, I might investigate to see about it if that is ok with the others. I really don't know what the etiquette is with contributing and don't want to step on any toes.

**Comment by lloydbayley** [comment]
Sorry...posted in wrong issue...was meant for #631
