### ISSUE TITLE
Problems with connecting the microphone

### ISSUE THREAD

**Issue by slinee** [mcguirepr89/BirdNET-Pi#665]
Hi!
I was trying to get the birnet pi set up but had some trouble with trying to connect the microphone with the raspberry pi. I followed the instructions on soldering a custom microphone and believe that I have done everything correctly but I can't seem to make my raspberry pi detect it. Any ideas on how to solve this issue? Thanks in advance! (This is the image of raspberry pi not detecting any capture hardware devices while having my microphone plugged in)
![316987424_510546761095011_8567806087544785087_n](https://user-images.githubusercontent.com/59441704/204342026-c8c7b118-1f6c-40da-a5d6-fe61612fc66b.jpg)

**Comment by lloydbayley** [comment]
A great deal depends on how you created your microphone, circuitry and soldering etc.
Try plugging a normal USB microphone in and make sure that works first. (Some webcams also have a mic built in which will do in a pinch).
