### ISSUE TITLE
Week Report % change incorrect.

### ISSUE THREAD

**Issue by jds3d** [mcguirepr89/BirdNET-Pi#666]
### PLEASE READ THE DOCUMENTATION BEFORE SUBMITTING AN ISSUE
**Describe the bug**

My Week 47 report shows:
= Top 10 Species =
Blue Jay - 432 (+1%)
Northern Cardinal - 380 (-91%)

My Week 46 report shows:
= Top 10 Species =
Northern Cardinal - 726 (+45%)
Blue Jay - 429 (-5%)

My Week 45 report shows:
= Top 10 Species =
Blue Jay - 452 (+14%)
Northern Cardinal - 397 (+30%)

The percentage changes are not correct.  For Blue Jay, it goes from:
452 to 429 to 432.  
That is a -5%, +1% change (which is exactly what it shows)

But for Northern Cardinal, it goes from:
392 to 726 to 380.
That is an 85% gain followed by a 48% loss.  
But it shows +45% and -91%.  
Correct calculations are:
(726/392) - 1 = 0.85
(380/726) - 1 = -0.48

Thanks!

**Comment by ehpersonal38** [comment]
Thank you for finding this issue, I've committed a fix to the repo, let me know if that works for you or not. Take care!
