### ISSUE TITLE
Choices in "Today's Detections" disappear

### ISSUE THREAD

**Issue by Svardsten53** [mcguirepr89/BirdNET-Pi#704]
### PLEASE READ THE DOCUMENTATION BEFORE SUBMITTING AN ISSUE
**Describe the bug**
In "Today's Detections the choices "Legacy view" and "Normal view" now disappear at the right top of the page when the content is fully loaded. It appears quickly before everything is loaded.

**To Reproduce**
Go to "Today's Detections" in menu.

**Expected behavior**
To see the choice at the top all the time.

**Screenshots**

**Additional context**
It worked when it was introduced. I have also tested by visiting other installations and tried other web browsers, but same result.

**Your build**
Raspberry Pi 4B

**Code or log snippets**

**Comment by ehpersonal38** [comment]
Thanks for the bug report!

I believe I've fixed the issue (and a few others I noticed along the way), so I'll close this now. Feel free to re-open it if you discover there's still any problems.
