### ISSUE TITLE
Some strange issue

### ISSUE THREAD

**Issue by Stepphenwolf2021** [mcguirepr89/BirdNET-Pi#718]
I just make my birdnet-pi project up 3 days ago. Everything seems to be fine and I have my station registerd in BirdWeather as station no. 710. (https://app.birdweather.com/stations/710).

As I have to shutdown my raspberry pi 3B every night and start it every morning. I notice that sometimes the recording function didn't work after the raspberry pi start. (The play icon on the right top corner is dimmed and can not be clicked). However, after I ssh login into the raspberry pi,  everything back to normal. This happen 2-3 times when I have to restart the raspberry pi.

Is that normal ? or Do I miss something during installation process ?

Please advise. 

Thank you

**Comment by blogdemoi** [comment]
Hello,
Out of topic... Is your Birdnet-Pi public? I would be happy to listen to Thai birds.
Thank you.

**Comment by ehpersonal38** [comment]
Try running the following commands:
`sudo systemctl enable getty@tty1.service`
`bash ~/BirdNET-Pi/scripts/restart_services.sh` (this one will take a minute to run)

**Comment by Stepphenwolf2021** [comment]
> 

Not yet, i am asking for fix public ip address from the service provider. Hope I can make it public within next week. However, you can listen Thai Bird at this site https://app.birdweather.com/stations/710

Cheers,

**Comment by Stepphenwolf2021** [comment]
> `sudo systemctl enable getty@tty1.service`
> `bash ~/BirdNET-Pi/scripts/restart_services.sh`

Thank you ehpersonal38. Do I need to run this command every time I restart or just once. Sorry for asking, I am very new for raspberry pi.

**Comment by ehpersonal38** [comment]
@Stepphenwolf2021 Just once 🙂

**Comment by Stepphenwolf2021** [comment]
Thank you everyone.

**Comment by Stepphenwolf2021** [comment]
@ehpersonal38  My birdnet-pi was not detect any bird for 2 days now. I did run your command many times, but it still does not work.

**Comment by ehpersonal38** [comment]
I'll need to see your View Logs, or `/var/log/syslog`

**Comment by DemBones78** [comment]
why do you have to shut it down every day ?  that's an odd problem to have.  if its a power issue they make a pi UPS 
https://www.amazon.com/gp/product/B08VS5HMLF/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B08VS5HMLF&linkCode=as2&tag=mklements-20&linkId=fbcfdd13281423cf5979cc2caf14312a&th=1

**Comment by DemBones78** [comment]
[Stepphenwolf2021](https://github.com/Stepphenwolf2021)

on the index page under amazing what does it say ?  
my unit has been over run with birds and is a day behind, processing 24x7    maybe you are just behind because you are turning it off every night.      

look at the image i posted its from my setup.  mine shows no detection today because its still working on yesterday

![Capture](https://user-images.githubusercontent.com/46800652/215849008-0aafd761-57b5-436b-9f03-71998a96bd5d.JPG)

**Comment by Stepphenwolf2021** [comment]
> Here are my screen shot

<img width="2226" alt="Screen Shot 2566-02-01 at 23 24 55" src="https://user-images.githubusercontent.com/90167629/216102683-0fd6ecf8-3c5d-4550-a100-aead96eca4bd.png">



> I'll need to see your logs with the following command: `tail -n 100 /var/log/syslog`

<img width="2226" alt="Screen Shot 2566-02-01 at 23 24 40" src="https://user-images.githubusercontent.com/90167629/216102620-653f0192-8745-403e-b085-4d65580b1f54.png">

**Comment by Stepphenwolf2021** [comment]
> on the index page under Analyzing what does it say?

Sorry, where is the index page ? I can't find it.

**Comment by Stepphenwolf2021** [comment]
> A lot of people have problems with the Raspberry Pi 3B, so it's not really recommended anymore. See this thread for a few commands you can run to hopefully help it run better, but no guarantees: [#242 (comment)](https://github.com/mcguirepr89/BirdNET-Pi/discussions/242#discussioncomment-2694098)

Sorry for make thing confusing, this log is from another raspberry pi 4

**Comment by ehpersonal38** [comment]
@Stepphenwolf2021 are you still facing this issue?
