### ISSUE TITLE
Unicode Encode Error

### ISSUE THREAD

**Issue by lloydbayley** [mcguirepr89/BirdNET-Pi#734]
Well, this is a bit of an odd one.
It has happened to me once before and I put it down to 'weird stuff happens' but it's happened again.
I noticed my recognitions had stopped and looked at the logs and saw the following:

![Image 9-2-23 at 5 12 pm](https://user-images.githubusercontent.com/21309308/217778081-34e35c03-40bd-414f-91bf-340f13fe318f.jpeg)

I'm wondering if there is some malformed text in Flickr descriptions...although, I'm not 100% sure.

In this case, it is encountering a right-single-quote and this is breaking the string continuity. It should be an apostrophe.
I'm having a good think about how we could sanitise the text coming in to be sent out via Apprise.

Afterthought, I'm wondering if enforcing encoding with `# encoding: utf-8` might help but then again that might break it globally....

Anyone else seen this?

**Comment by ehpersonal38** [comment]
Good spot! It's a little annoying that my try/except had an exception... >_>

I think you've described the problem pretty well, a weird character in the title of a Flickr image. I've just done a commit which may or may not address this issue. Time will tell I guess

Thanks again for the report!

**Comment by lloydbayley** [comment]
Well don't you get a gold star?! :) That was quick.
Will be interested to see your catchall. I shall keep an eye on this to see how it goes!
Thanks @ehpersonal38 !
