### ISSUE TITLE
Failure to install since requirements updated

### ISSUE THREAD

**Issue by DrBazUK** [mcguirepr89/BirdNET-Pi#769]
For a variety of reasons I have been installing and reinstalling Birdnet.pi on Raspbian and other OS's today. However I am now getting a failure to install with the following error:

+ pip3 install -U -r /home/birder/BirdNET-Pi/requirements.txt
ERROR: Invalid requirement: 'streamlit=1.11.1' (from line 11 of /home/birder/Bir
Hint: = is not a valid operator. Did you mean == ?
The installation exited unsuccessfully.

**To Reproduce**
1. Install Raspbian 64bit lite OS and write image using Raspberry Pi imager including user details specified in https://github.com/mcguirepr89/BirdNET-Pi/wiki/Installation-Guide
2. SSH into Raspberry pi using Putty
3. Copy and paste BASH script "curl -s https://raw.githubusercontent.com/mcguirepr89/BirdNET-Pi/main/newinstaller.sh | bash"
4. Run through updates until script fails with error above.

**Expected behavior**
It should run without error and has done multiple times today (Tuesday 28 Feb) - I don't know enough code to know if the error is simply a missing = when declaring the variable or not.

**Your build**
Currently installing on Raspberry Pi 4 4GB model.

**Comment by DrBazUK** [comment]
Have forked and confirmed that with the suggested edit to add a =, the script completes successfully. Maybe you'll make a coder of me yet :D

**Comment by ehpersonal38** [comment]
*facepalms. I swear I even doubled checked it before committing!! Thank you for finding this issue!

> Have forked and confirmed that with the suggested edit to add a =, the script completes successfully. Maybe you'll make a coder of me yet :D

Ah yes, I meant to say -- this was an intentional bug to give new contributors a chance to contribute to the repo. Haha

**Comment by DrBazUK** [comment]
> *facepalms. I swear I even doubled checked it before committing!! Thank you for finding this issue!
> 
> > Have forked and confirmed that with the suggested edit to add a =, the script completes successfully. Maybe you'll make a coder of me yet :D
> 
> Ah yes, I meant to say -- this was an intentional bug to give new contributors a chance to contribute to the repo. Haha

Love the intent - I've been hovering around doing bits with code for too long - am finally getting some time to do something about it. Now sleep beckons - 0230hrs -
