### ISSUE TITLE
Birdnet showing non english names for birds

### ISSUE THREAD

**Issue by Punkley** [mcguirepr89/BirdNET-Pi#788]
Names for birds are using non english names, when, latin names exist.

See attached
![image](https://user-images.githubusercontent.com/29708979/226042564-02881e1d-85bd-4e56-918c-50f17ed0a953.png)

Kingsley

**Comment by ehpersonal38** [comment]
Hi, can you run the following command in your Pi's terminal and copy/paste the output?

`~/BirdNET-Pi/scripts/birds.db "SELECT com_name FROM detections GROUP BY com_name;"`

**Comment by lloydbayley** [comment]
Might want to bung an sqlite3 in there to make:
```
sqlite3 ~/BirdNET-Pi/scripts/birds.db "SELECT com_name FROM detections GROUP BY com_name;"
```

**Comment by Punkley** [comment]
sqlite3 ~/BirdNET-Pi/scripts/birds.db "SELECT com_nam                                                    e FROM detections GROUP BY com_name;"
Australian Magpie
Black-faced Cuckooshrike
Crimson Rosella
Eastern Yellow Robin
Galah
Little Corella
Little Raven
Little Wattlebird
Magpie-lark
Mistletoebird
Musk Lorikeet
New Holland Honeyeater
Pied Butcherbird
Rainbow Lorikeet
Red Wattlebird
Southern Boobook
Spotted Dove
Sulphur-crested Cockatoo
Weebill
Willie-wagtail
Yellow-tailed Black-Cockatoo
Горобець хатній
Дрізд чорний
Коловодник болотяний
Сапсан
Сипуха

**Comment by ehpersonal38** [comment]
I suppose you changed your database language to Russian for a little while? I recommend removing those entries from the database so they don't appear in the web interface anymore.

`sqlite3 ~/BirdNET-Pi/scripts/birds.db "DELETE FROM detections WHERE com_name IN ('Горобець хатній', 'Дрізд чорний', 'Коловодник болотяний', 'Сапсан', 'Сипуха')"
`

**Comment by Punkley** [comment]
Never was russian and it is still happening today, I am using the v2.2 DB if that helps
![image](https://user-images.githubusercontent.com/29708979/226140194-e4d6ea4e-6bf2-495e-b76b-bfbfbef9ab18.png)

Kingsley

**Comment by ehpersonal38** [comment]
Can I see the output of this command?

`ls -lh ~/BirdNET-Pi/model`

**Comment by Punkley** [comment]
oh looked, I was using label_uk.txt I have changed it to label_en.txt

**Comment by ehpersonal38** [comment]
Yeah that's Ukranian - closing this issue now.
