### ISSUE TITLE
Apprise Notifications Not Saving On Update

### ISSUE THREAD

**Issue by paulhoff** [mcguirepr89/BirdNET-Pi#793]
I put info into the apprise notification section.  The send test message works successfully.  However, when I push update all the info I have entered disappears.

**Comment by ehpersonal38** [comment]
Interesting. Are you on the latest update? Also please run the following command on your Raspberry Pi and copy and paste the output of your birdnet.conf. You will need to censor any sensitive data such as passwords, API keys, etc:

`cat ~/BirdNET-Pi/birdnet.conf`

**Comment by paulhoff** [comment]
Thanks.  I am not sure how to check what version I am running.  I am
running the most updated version from
https://github.com/mcguirepr89/BirdNET-Pi
<https://mailtrack.io/trace/link/89781f98e1e53948dd52b4cc579ca6f16446546a?url=https%3A%2F%2Fgithub.com%2Fmcguirepr89%2FBirdNET-Pi&userId=867221&signature=b433c6e79f2d6d8b>

Also the Apprise.txt contains nothing.

conf is below.


birdnet:~/BirdNET-Pi$ cat birdnet.conf
################################################################################
#                    Configuration settings for BirdNET-Pi
   #
################################################################################

# Optional: Site Title for banner

SITE_NAME="birdnet"

#--------------------- Required: Latitude, and Longitude
----------------------#

## The shell substitution below guesses these based on your network. THESE
NEED
## TO BE CHANGED TO STATIC VALUES
## Please only go to 4 decimal places. Example:43.3984


LATITUDE=redadcted
LONGITUDE=-104.9431

#--------------------------------- Model
--------------------------------------#
#_____________The variable below configures which BirdNET model
is_____________#
#______________________used for detecting bird
audio.__________________________#
#_It's recommended that you only change these values through the web
interface.#

MODEL=BirdNET_GLOBAL_3K_V2.2_Model_FP16
SF_THRESH=0.03

#---------------------  BirdWeather Station Information
-----------------------#
#_____________The variable below can be set to have your
BirdNET-Pi____________#
#__________________also act as a BirdWeather listening
station_________________#

BIRDWEATHER_ID=Egwne6wjeX7fv4zHmroYMR8A

#-----------------------  Web Interface User Password
------------------------#
#____________________The variable below sets the
'birdnet'_____________________#
#___________________user password for the Live Audio
Stream,___________________#
#_________________Tools, System Links, and the Processed files
________________#

## CADDY_PWD is the plaintext password (that will be hashed) and used to
access
## certain parts of the web interface

CADDY_PWD="redacted"

#-------------------------  Live Audio Stream
--------------------------------#
#_____________The variable below configures/enables the
live___________________#
#_____________________________audio
stream.____________________________________#


## ICE_PWD is the password that icecast2 will use to authenticate ffmpeg as
a
## trusted source for the stream. You will never need to enter this manually
## anywhere other than here and it stays on 'localhost.'

ICE_PWD=birdnetpi

#-----------------------  Web-hosting/Caddy File-server
-----------------------#
#_______The three variables below can be set to enable internet
access_________#
#____________to your data,(e.g., extractions, raw data,
live___________________#
#______________audio stream, BirdNET.selection.txt
files)______________________#


## BIRDNETPI_URL is the URL where the extractions, data-set, and live-stream
## will be web-hosted. If you do not own a domain, or would just prefer to
keep
## the BirdNET-Pi on your local network, keep this EMPTY.

BIRDNETPI_URL=

#----------------------------  RTSP Stream URL
-------------------------------#

## If RTSP_STREAM is set, the system will use the RTSP stream as its audio
## source instead of recording its own audio. If this variable is kept
empty,
## BirdNET-Pi will default to recording its own audio.

RTSP_STREAM=

#-----------------------  Apprise Miscellanous Configuration
-------------------#

APPRISE_NOTIFICATION_TITLE="New BirdNET-Pi Detection"
APPRISE_NOTIFICATION_BODY='A $sciname $comname was just detected with a
confidence of $confidence'
APPRISE_NOTIFY_EACH_DETECTION=0
APPRISE_NOTIFY_NEW_SPECIES=0
APPRISE_WEEKLY_REPORT=0
APPRISE_NOTIFY_NEW_SPECIES_EACH_DAY=0
APPRISE_MINIMUM_SECONDS_BETWEEN_NOTIFICATIONS_PER_SPECIES=300

#----------------------  Flickr Images API Configuration
-----------------------#
## If FLICKR_API_KEY is set, the web interface will try and display bird
images
## for each detection. If FLICKR_FILTER_EMAIL is set, the images will only
be
## displayed from a particular Flickr user (e.g. yourself).

FLICKR_API_KEY=redacted
FLICKR_FILTER_EMAIL=

################################################################################
#--------------------------------  Defaults
----------------------------------#
################################################################################

## RECS_DIR is the location birdnet_analysis.service will look for the
data-set
## it needs to analyze. Be sure this directory is readable and writable for
## the BIRDNET_USER.

RECS_DIR=/home/admin/BirdSongs

## REC_CARD is the sound card you would want the birdnet_recording.service
to
## use. Leave this as "default" to use PulseAudio (recommended), or use
## the output from "aplay -L" to specify an ALSA device.

REC_CARD="default"

## PROCESSED is the directory where the formerly 'Analyzed' files are moved
## after extractions have been made from them. This includes both WAVE and
## BirdNET.selection.txt files.

PROCESSED=/home/admin/BirdSongs/Processed

## EXTRACTED is the directory where the extracted audio selections are
moved.

EXTRACTED=/home/admin/BirdSongs/Extracted

## OVERLAP is the value in seconds which BirdNET should use when analyzing
## the data. The values must be between 0.0-2.9.

OVERLAP=0.0

## CONFIDENCE is the minimum confidence level from 0.0-1.0 BirdNET's
analysis
## should reach before creating an entry in the BirdNET.selection.txt file.
## Don't set this to 1.0 or you won't have any results.

CONFIDENCE=0.75

## SENSITIVITY is the detection sensitivity from 0.5-1.5.

SENSITIVITY=1.25

## Configuration of the frequency shifting feature, useful for earing
impaired people.

## FREQSHIFT_TOOL

FREQSHIFT_TOOL=sox

## If the tool is ffmpeg, you have to define a freq. shift from HI to LO:
## FREQSHIFT_HI
FREQSHIFT_HI=6000
## FREQSHIFT_LO
FREQSHIFT_LO=3000

## If the tool is sox, you have to define the pitch shift (amount of 100ths
of semintone)
## FREQSHIFT_PITCH
FREQSHIFT_PITCH=-1500

## CHANNELS holds the variable that corresponds to the number of channels
the
## sound card supports.

CHANNELS=2

## FULL_DISK can be set to configure how the system reacts to a full disk
## purge = Remove the oldest day's worth of recordings
## keep = Keep all data and 'stop_core_services.sh'

FULL_DISK=purge

## PRIVACY_THRESHOLD can be set to enable sensitivity to Human sounds. This
## setting is an effort to introduce privacy into the data collection.
## The PRIVACY_THRESHOLD value represents a percentage of the entire species
## list used during analysis. If a human sound is predicted anywhere within
## the precentile set below, no data is collected for that audio chunk.
## Valid range: 0-3

PRIVACY_THRESHOLD=0

## RECORDING_LENGTH sets the length of the recording that BirdNET-Lite will
## analyze.

RECORDING_LENGTH=15

## EXTRACTION_LENGTH sets the length of the audio extractions that will be
made
## from each BirdNET-Lite detection. An empty value will use the default of
6
## seconds.

EXTRACTION_LENGTH=

## AUDIOFMT set the audio format that sox should use for the extractions.
## The default is mp3. Available formats are: 8svx aif aifc aiff aiffc al
amb
## amr-nb amr-wb anb au avr awb caf cdda cdr cvs cvsd cvu dat dvms f32 f4
f64 f8
## fap flac fssd gsm gsrt hcom htk ima ircam la lpc lpc10 lu mat mat4 mat5
maud
## mp2 mp3 nist ogg paf prc pvf raw s1 s16 s2 s24 s3 s32 s4 s8 sb sd2 sds
sf sl
## sln smp snd sndfile sndr sndt sou sox sph sw txw u1 u16 u2 u24 u3 u32 u4
u8
## ub ul uw vms voc vorbis vox w64 wav wavpcm wv wve xa xi
## Note: Most have not been tested.

AUDIOFMT=mp3

## DATABASE_LANG is the language used for the bird species database
DATABASE_LANG=en

## HEARTBEAT_URL is a location to ping every time some analysis is done
## no information is sent to the the URL, its a heart beat to show that the
## analysis is continuing

HEARTBEAT_URL=

## SILENCE_UPDATE_INDICATOR is for quieting the display of how many commits
## your installation is behind by, relative to the Github repo. This number
## appears next to "Tools" when you're 50 or more commits behind.

SILENCE_UPDATE_INDICATOR=0

## These are just for debugging
LAST_RUN=
THIS_RUN=
IDFILE=/home/admin/BirdNET-Pi/IdentifiedSoFar.txt
RAW_SPECTROGRAM=0
CUSTOM_IMAGE=
CUSTOM_IMAGE_TITLE=""

**Comment by ehpersonal38** [comment]
Thanks, your config all looks good there. I'm thinking this is a permissions issue. Can you please run the following command and copy and paste the output here so I can take a look?

`ls -lh ~/BirdNET-Pi/`

**Comment by soumilgurjar** [comment]
I faced the same issue when setting up my apprise notifications despite being on the latest update. As mentioned by @ehpersonal38 , it was indeed a permissions issues and the solution was changing permissions as described in https://github.com/mcguirepr89/BirdNET-Pi/discussions/381#discussioncomment-3005877 .

**Comment by ehpersonal38** [comment]
@soumilgurjar Thanks for bringing this to my attention! I did fairly recently change some code which set the permissions for BirdNET-Pi related files. I thought it was a harmless fix but apparently not. I've just done a commit now which should hopefully sort out all of this.

@paulhoff Go ahead and update your system via Tools -> System Controls -> Update, and please see if your issue is fixed.

**Comment by paulhoff** [comment]
I updated to the most recent, rebooted.  That did NOT fix the problem.  However following the permissions command from #381 did fix it.  Thanks for all the help.
