### ISSUE TITLE
library (audioread, librosa) log errors - won't restart processing

### ISSUE THREAD

**Issue by Normanras** [mcguirepr89/BirdNET-Pi#798]
**Describe the bug**
After a hard reset due to a power outage, I get `audioread` errors in my logs and the processing of audio files won't continue. Here is the log. It just shows this after a _proper_ reboot and nothing else. See below for logs.

**To Reproduce**
1. Hard reset RasberryPi without a proper reboot
2. Errors in log don't show anything beyond the above error lines.

**Expected behavior**
1. If there are errors, I would expect them to log it but then continue processing the rest of the audio files. 

**Screenshots**

**Additional context**
None

**Your build**
RaspberryPi 3b+
Model: BirdNET_GLOBAL_3K_V2.2_Model_FP16 (2022)

**Code or log snippets**

```
Journal file /var/log/journal/610078df7145487db543439a6d2752fb/system@0005f773c17ad4ec-cdae9b279fcc8223.journal~ is truncated, ignoring file.
09:59:15---    sig, rate = librosa.load(path, sr=sample_rate, mono=True, res_type='kaiser_fast')
09:59:15---  File "BirdNET-Pi/birdnet/lib/python3.9/site-packages/librosa/util/decorators.py", line 88, in inner_f
09:59:15---    return f(*args, **kwargs)
09:59:15---  File "BirdNET-Pi/birdnet/lib/python3.9/site-packages/librosa/core/audio.py", line 170, in load
09:59:15---    y, sr_native = __audioread_load(path, offset, duration, dtype)
09:59:15---  File "BirdNET-Pi/birdnet/lib/python3.9/site-packages/librosa/core/audio.py", line 226, in __audioread_load
09:59:15---    reader = audioread.audio_open(path)
09:59:15---  File "BirdNET-Pi/birdnet/lib/python3.9/site-packages/audioread/__init__.py", line 132, in audio_open
09:59:15---    raise NoBackendError()
09:59:15---audioread.exceptions.NoBackendError
```

**Comment by Normanras** [comment]
Since I only had a few days of data in my setup, I cleared all data under system options, which solved the problem. Processing is working again. 

But I'd like to avoid or solve this without clearing all my data. If you have any suggestions, please let me know!

**Comment by ehpersonal38** [comment]
I wonder if an audio file got corrupted during the power outage which messed things up. In that case running Tools -> Services -> Restart core services will clear all unprocessed data while still preserving the data in your database.

**Comment by ehpersonal38** [comment]
I believe you'll have to remove the detection associated with the corrupted file from the database as well. This definitely should be handled automatically somehow in the code but alas. Hopefully you're able to sort this out should it arise again!

**Comment by Normanras** [comment]
I'll for sure figure it out - but hopefully it doesn't happen again! Thanks again for this amazing work.

**Comment by Normanras** [comment]
@ehpersonal38 power brown out last night, and this morning the same issue is happening. The only difference this time is I can't seem to suss out if it's a particular file that needs to be deleted or the whole day/species. 

If you're game for it, I'd say let's try and debug this step by step. I've read through the codebase a few times already so I'm happy to do the work of writing the fix and PR.

My hunch is first to see where the corrupted file is and why the library/service gets stuck there. Open to your instructions and suggestions.

**Comment by ehpersonal38** [comment]
Sure - we can try to debug this! Do the logs show any indication of the actual file path that the script is getting hung up on?

**Comment by Normanras** [comment]
Ok, sorry for the play by play but we're back in action. Looks like the PR should be an error handler in `spectrogram.sh`. If that service exits, remove the file and increment `analyzing_now.txt` to the next file in the recordings. 

Somehow notifying users of the error would be a bonus, but idk most would care.

**Comment by ehpersonal38** [comment]
Hmm, so on my system if I put some non-existent file path in `analyzing_now.txt`, the spectrogram service _does_ fail, but it quickly starts working again because every 15 seconds `birdnet_analysis.sh` is overwriting `analyzing_now.txt` with the most current file path. So I'm not really sure why your system is getting hung up?

You can see the code where `birdnet_analyzer.sh` does this: https://github.com/mcguirepr89/BirdNET-Pi/search?q=analyzing_now

**Comment by Normanras** [comment]
So the spectrogram service fails but doesn't exit? I'm wondering now why the lack of RIFF header caused mine to fail and exit. 

I'm going to try and run the analyzer with more verbosity later and either create/find a wav file without the header or do a hard restart.

**Comment by ehpersonal38** [comment]
Yeah it fails and exits. But the service restarts itself automatically whenever it exits and fails.

```
$ cat /home/pi/BirdNET-Pi/templates/spectrogram_viewer.service
[Unit]
Description=BirdNET-Pi Spectrogram Viewer
[Service]
Restart=always
RestartSec=10
Type=simple
User=pi
ExecStart=/usr/local/bin/spectrogram.sh
```

**Comment by Normanras** [comment]
Man, this is weird. I've downloaded all the logs from 8am that day (well before it was turned back on) up until after the timestamp of this issue. All I see is the sequence of events we know about, which is:

1. Pi boots, no errors.
2. This is the last time we see `birdnet_analysis.sh` writing anything to the logs. The timestamp and last command:
```
Mar 26 10:27:28 birdpinet birdnet_analysis.sh[11860]: Files loaded
Mar 26 10:27:29 birdpinet birdnet_analysis.sh[11860]: RECORDING_LENGTH set to 30
Mar 26 10:27:29 birdpinet birdnet_analysis.sh[11860]: /home/birdpi/BirdNET-Pi/birdnet/bin/python3 /home/birdpi/BirdNET-Pi/scripts/analyze.py --i /home/birdpi/BirdSongs/March-2023/26-Sunday/2023-03-26-birdnet-09:42:42.wav --o /home/birdpi/BirdSongs/March-2023/26-Sunday/2023-03-26-birdnet-09:42:42.wav.csv --lat 41.XX --lon -73.XX --week 12 --overlap 0.0 --sensitivity 1.25 --min_conf 0.7 --birdweather_id "IN_USE"
```
3. This error occurs right after:
`Mar 26 09:46:44 birdpinet python3[369]: READING AUDIO DATA... /home/birdpi/BirdNET-Pi/birdnet/lib/python3.9/site-packages/librosa/util/decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.`
4. Seeing the error, I manually restart core services. 
5. This error then occurs:
```
Mar 26 09:46:49 birdpinet systemd[1]: Stopped BirdNET-Pi Spectrogram Viewer.
Mar 26 09:46:49 birdpinet systemd[1]: Started BirdNET-Pi Spectrogram Viewer.
Mar 26 09:46:49 birdpinet spectrogram.sh[1461]: sox FAIL formats: can't open input file `/home/birdpi/BirdSongs/March-2023/26-Sunday/2023-03-26-birdnet-09:42:42.wav': WAVE: RIFF header not found
```
6. This continues every ~10 seconds. I see myself ssh into the machine and creating a session. 
7. Then, around 11 am, I have deleted the file because a new error appears. This aligns with the time in the comments above. 
```
Mar 26 11:02:41 birdpinet spectrogram.sh[25006]: sox FAIL formats: can't open input file `/home/birdpi/BirdSongs/March-2023/26-Sunday/2023-03-26-birdnet-09:42:42.wav': No such file or directory
Mar 26 11:02:41 birdpinet systemd[1]: spectrogram_viewer.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 26 11:02:41 birdpinet systemd[1]: spectrogram_viewer.service: Failed with result 'exit-code'.
```
8. This error also continues every ~10 seconds. As stated above, `birdnet_analysis.sh` does not show up anywhere in these sections of the logs, meaning that the script isn't overwriting the `analyzing_now.txt`. 
9. So now at 11:21, you see my ssh session start, end, and then the above error of `No such file or directory` disappears.
10. `birdnet_analysis.sh` shows up again, everything is working.  

What's interesting is your test, @mcguirepr89, of manually writing a fake file to `analyzing_now.txt` and how the program just moves past it. However, with a corrupted file, the `audioread` and associated libraries fail because the file isn't read correctly. This is a hunch, but perhaps the library possibly tanks the script altogether and it requires a manual push to restart. 

I'm going to create a fake `wav` file with the same filename formatting for 10 minutes ahead of where `birdnetpi` is currently at and see what happens when it reaches the file. 

It may be a simple fix of error handling in the logs. I'll come back to this after a few tests.

**Comment by ehpersonal38** [comment]
```
Mar 26 09:46:44 birdpinet python3[369]: READING AUDIO DATA... /home/birdpi/BirdNET-Pi/birdnet/lib/python3.9/site-packages/librosa/util/decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
```

Okay so this gives me a big clue as to what's happening. This is an error thrown from `server.py`. So I think we need a try/except block around where `server.py` processes the audio files.

**Comment by Normanras** [comment]
Okay, that should be straight forward enough. Good find. I didn't see any contribution guidelines/tests or anything in the wiki - good for me to open a PR?

**Comment by ehpersonal38** [comment]
@Normanras Yep you're free to open a PR!

**Comment by Normanras** [comment]
Okay, it took me a bit with work, but I've added a branch with the changes. Before I submit it do you have a standard testing operation? I notice `tests` is for the settings/conf file and apprise.

**Comment by ehpersonal38** [comment]
@Normanras Nope, no official testing procedure. As long as it works then I'm happy.
