### ISSUE TITLE
Cant update advanced settings: Fatal error

### ISSUE THREAD

**Issue by ampsu** [mcguirepr89/BirdNET-Pi#813]
I get an error when I am tring to update advanced settings:
`Fatal error: Uncaught Error: Call to undefined function isNumeric() in /home/USER/BirdNET-Pi/scripts/advanced.php:104 Stack trace: #0 /home/USER/BirdNET-Pi/homepage/views.php(157): include() #1 {main} thrown in /home/USER/BirdNET-Pi/scripts/advanced.php on line 104`

It started after updating to latest version :( Any ideas?

**Comment by ehpersonal38** [comment]
Oops, that's embarassing (my code). Please update again and let me know if that fixes things!

**Comment by ampsu** [comment]
It worked! Thank you :D
