### ISSUE TITLE
Add option for Privacy Policy

### ISSUE THREAD

**Issue by dpkgbofh** [mcguirepr89/BirdNET-Pi#843]
Hi Patrick,

in Europe we are obliged to have a link to a privacy policy page on every public web page.
I have been manually adding this to the index.php:
![image](https://user-images.githubusercontent.com/67900136/231075788-c991fa04-2e09-4e4e-bae5-dc8c7322a59c.png)

It'd be nice to have this done more professionally and as an option in the configuration.

Thanks so much for all your splendid work!
Cheers, Jan

**Comment by matthew73210** [comment]
> Hi Patrick,
> 
> in Europe we are obliged to have a link to a privacy policy page on every public web page. I have been manually adding this to the index.php: ![image](https://user-images.githubusercontent.com/67900136/231075788-c991fa04-2e09-4e4e-bae5-dc8c7322a59c.png)
> 
> It'd be nice to have this done more professionally and as an option in the configuration.
> 
> Thanks so much for all your splendid work! Cheers, Jan

Hello,

It's not a public page. And really shouldn't be. Only if you want it to be, and the author describes the whatnot. So the onus is on the user in my opinion. There is an option to upload to birdweather which gives all the info needed plus privacy protection as you quoted.

Cheers :)

**Comment by dpkgbofh** [comment]
Point taken ;)
I'd be nice anyway, and not a big deal to code, is it?
Cheers, Jan

**Comment by lloydbayley** [comment]
My opinion is, I think it would be tricky to make something that 'pleases' all areas requirements as they might differ and it's really up to the system administrator to ensure the privacy for that area. It's a point which has been thrashed about in #166 and quite a bit has been done to improve 'privacy'. Have a read of that and see what you think.

**Comment by lloydbayley** [comment]
I know what you want but I was just pointing out why it may not have been done. Perhaps @ehpersonal38 has some thoughts on this. He gets busy but I'm sure he'll see this at some stage soon.

**Comment by ehpersonal38** [comment]
Since BirdNET-Pi doesn't collect user data does it still need a privacy policy?

I feel like the onus of complying with local laws is on the person hosting the website. Otherwise we'd have to accommodate like every single country's privacy laws which would be unreasonable in my opinion. 

Thoughts?

**Comment by lloydbayley** [comment]
I concur.

**Comment by matthew73210** [comment]
> Since BirdNET-Pi doesn't collect user data does it still need a privacy policy?
> 
> I feel like the onus of complying with local laws is on the person hosting the website. Otherwise we'd have to accommodate like every single country's privacy laws which would be unreasonable in my opinion.
> 
> Thoughts?

I know that in Europe, if you have cookies on you website they must be made known. Kinda massive rabbit hole best not explored. The fact that you can record human voice, even with a filter makes it already dubious. So i'd stick to bird weather and keep the webpage 100% private (owner discretion after that)
