### ISSUE TITLE
"Close" Flickr image not visible on mobile

### ISSUE THREAD

**Issue by ehpersonal38** [mcguirepr89/BirdNET-Pi#876]
**Describe the bug**
On mobile if you open a Flickr image, the close button at the bottom is obscured and unable to be clicked.

**Comment by lloydbayley** [comment]
Oh YUCK. That's going to be a bugger...investigating...

**Comment by lloydbayley** [comment]
That's weird, I can't replicate this. It works ok on mine with the only requirement being scrolling by swiping up on the text, not the picture.

**Comment by ehpersonal38** [comment]
@lloydbayley where'd your comments go? I tried what you said (scrolling on the text and not the picture) and it led me to discover the root of this problem. Will push a fix shortly!

**Comment by lloydbayley** [comment]
Ahh...I second-guessed myself and thought I didn't know what I was talking about so I zapped my ramblings. Turns out, from looking at your commit, it was exactly where I was poking about. Nevermind.

**Comment by ehpersonal38** [comment]
Don't second guess! Your contributions are valuable here!
