### ISSUE TITLE
Change in the translation of species causes duplications in the database.

### ISSUE THREAD

**Issue by raulgalindomoreno** [mcguirepr89/BirdNET-Pi#924]
### PLEASE READ THE DOCUMENTATION BEFORE SUBMITTING AN ISSUE
**Describe the bug**
In the Spanish translation, the second word of the name has been capitalised. This causes each species to appear twice, with the old and the new translation. This has been the case at least since 27 March. On the other hand, in Spanish, bird names are not capitalised.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem or your installation here.

**Your build**
The hardware on which BirdNET-Pi is running goes here.

**Code or log snippets**
```
<img width="224" alt="Captura de pantalla 2023-05-23 a las 18 53 32" src="https://github.com/mcguirepr89/BirdNET-Pi/assets/128041444/08a25f70-781a-4856-b1bb-4a0b6e7d3e5e">

Paste your 
log output 
or 
code here
```

**Comment by ehpersonal38** [comment]
Hi,

BirdNET-Pi doesn't manage the species label files for the model, I recommend directing your feedback to the model repo here: https://github.com/kahst/BirdNET-Analyzer
