### ISSUE TITLE
minor issue: format of no. of detections

### ISSUE THREAD

**Issue by DD4WH** [mcguirepr89/BirdNET-Pi#94]
![grafik](https://user-images.githubusercontent.com/14326464/145372437-4c3f5761-45e8-41b3-a962-2a14b3993d63.png)

I noticed that the no. of detections is formatted as "2e+x" when it exceeds 100.
It would be desirable to have the no. of detections (for each hour) stated as "124", instead of "2e+024"

**Comment by mcguirepr89** [comment]
I'll get with @CaiusX and I bet we'll be able to adjust that

**Comment by mcguirepr89** [comment]
@CaiusX I found [this](https://michael-fuchs-python.netlify.app/2019/04/28/how-to-suppress-scientific-notation-in-pandas/) and will see what kind of results I can come up with

**Comment by DD4WH** [comment]
May I suggest something else that is related to rounding  scientific notation ?
Could the confidence scores be expressed as % and rounded to one digit after the decimal point [eg. 92.4%] ? Three digits are more than enough and we do not need that kind of precision, I think ;-)

**Comment by mcguirepr89** [comment]
>May I suggest something else that is related to rounding / scientific notation ?
Could the confidence scores be expressed as % and rounded to one digit after the decimal point [eg. 92.4%] ? Three digits are more than enough and we do not need that kind of precision, I think ;-)

Noted!

**Comment by mcguirepr89** [comment]
[How's this?](https://birdnetpi.pmcgui.xyz/viewdb.php)

**Comment by mcguirepr89** [comment]
I've pulled the new percentages view and _suppressing scientific notation_ into main, so you should be able to use the "Update BirdNET-Pi" "Tool" to get those changes into your system

**Comment by mcguirepr89** [comment]
@CaiusX's results:
![image](https://user-images.githubusercontent.com/60325264/145444432-8d294539-9aff-47e7-a034-e013edabfa59.png)
