### ISSUE TITLE
Availability of netstat tool necessary, but not checked at installation procedure

### ISSUE THREAD

**Issue by joberreiter** [mcguirepr89/BirdNET-Pi#945]
The recording service relies on the output of "netstat", but the install script does not check if that package is actually available.
If "netstat" is not available (aka "net-tools" package is not installed), the recording silently fails due to the following code in /usr/local/bin/birdnet_recording.sh:

```
  if pgrep arecord &> /dev/null ;then
    echo "Recording"
  else
    until grep 5050 <(netstat -tulpn 2>&1);do
      sleep 1
    done
    [...]
fi
```
**Expected behavior**
"netstat" should be checked at installation, or the log may be showing that the recording is in "sleep" mode (maybe only if the duration of the sleep mode exceeds a certain time?).

**Build / Hardware info**
- BirdNET-Pi v0.13, commit [92d083a](https://github.com/mcguirepr89/BirdNET-Pi/commit/92d083a14c74a8051616e5d6ef351713d5888d1c)
- Linux rock4se 5.10.110-8-rockchip #f9d1b1529 SMP Fri May 12 14:07:29 UTC 2023 aarch64 GNU/Linux
- Radxa ROCK 4 SE powered by RK3399-T with a dual core Cortex-A72 @1.5GHz and quad core Cortex-A53@1GHz ARM processor, 4GB 64bit LPDDR4.
- microphone MOVO USB-M1
 
[installation-2023-06-05.txt](https://github.com/mcguirepr89/BirdNET-Pi/files/11687285/installation-2023-06-05.txt)

**Comment by ehpersonal38** [comment]
Thanks for the PR! Merged.
