### ISSUE TITLE
Daily Chart

### ISSUE THREAD

**Issue by BobSpong** [mcguirepr89/BirdNET-Pi#961]
The Daily Chart on my build started intermittently updating and now has completely disappeared from the overview and specific page. Is there a way to refresh this code or indeed run something different like the full daily rundown rather than top 10?

**Comment by croisez** [comment]
I think that if you want to get help on your issue, you would better have to give us something to eat: error logs, traces, screen captures, etc.

**Comment by BobSpong** [comment]
Rebuilt and that fixed it
