### ISSUE TITLE
Selected Wrong User during Update

### ISSUE THREAD

**Issue by rezeero25** [mcguirepr89/BirdNET-Pi#971]
In the installation guide there is a note: "installing BirdNET-Pi on top of other servers is not supported"
But not that the execution of the script 

~~~
curl -s https://raw.githubusercontent.com/mcguirepr89/BirdNET-Pi/main/newinstaller.sh | bash
~~~ 

must be done with the user ID 1000. The comprehensive installation guide recommends a new/fresh install and using the freshly created (first) user (therefore with UID 1000)

When installing the Birdnet script as another user, there is an error when updating that the paths are no longer correct.
Because is in the fixed UID of 1000

~~~
USER=$(awk -F: '/1000/ {print $1}' /etc/passwd)
HOME=$(awk -F: '/1000/ {print $6}' /etc/passwd)
~~~
https://github.com/mcguirepr89/BirdNET-Pi/blob/c85fa1e9280b79fadc2867416f5b25fea0aa30c2/scripts/update_birdnet_snippets.sh#L5C1-L5C48

After installing BirdNet-Pi on a machine with already existing user (e.g. "first_user", the update tries to find the BirdNET-Pi path in the home directory of the user "first_user" (/home/first_user/BirdNET-Pi/scripts/*.txt') and not in the path /home/birdnet/.

So maybe an information to run installation only with user with UID 1000, or a quick guide to change the user-id:

**Comment by joberreiter** [comment]
This is a known issue, see also #947.
According to @ehpersonal38, they won't fix it ...

**Comment by joberreiter** [comment]
Try this to change it to the userid of the user running the command:
`grep -rl '/1000/' ~/BirdNET-Pi/ | xargs sed --quiet 's=/1000/=/$(id -u)/=g'`

You can replace `$(id -u)` with the desired user id of course.

**Comment by rezeero25** [comment]
Thanks for your comment.
I'm worried that after an update these changes will be undone. so I did the following:

Use a root account, or the other ("first" user).

Check with 
~~~
id username
~~~

for your first user and birdnet user the UID and GID, and in which other groups is included.

Change the old user, which has the UID=1000 to e.g. 2000 and the UID from the birdnet user to 1000. For this you may have to stop all services from the birdnet, additionally I force quit all running processes and logged out the user
~~~
sudo pkill -u birdnet
~~~

To change UID and GID:
~~~
usermod -u 1000 birdnet
groupmod -g 1000 birdnet
~~~
to add user to different groups (e.g. the birdnet user didnt had permission for audio):

At the end the result of ~~~id birdnet~~~ should something like this:

uid=1000(birdnet) gid=1000(birdnet) Groups=1000(birdnet),4(adm),20(dialout),24(                                                  cdrom),27(sudo),29(audio),44(video),46(plugdev),60(games),100(users),104(input),                                                  106(render),108(netdev),999(spi),998(i2c),997(gpio),117(lpadmin)


However, I don't know if this will still correctly assign old read/write permissions for folders and files

Hopefully that helps other. And we can close this "issue".

Another issue with this topic: https://github.com/mcguirepr89/BirdNET-Pi/pull/909
(I only found the old topics because now i know for what to look/search for)

**Comment by rezeero25** [comment]
> Run this once to change it to the userid of the user BirdNET is running under: `grep -rl '/1000/' ~/BirdNET-Pi/ | xargs sed --quiet 's=/1000/=/$(id -u)/=g'`
> 
> You can replace `$(id -u)` with the desired user id of course.

This will search and replace all "/1000/" in all files in BirdNET-Pi folder e.g. scripts/update_birdnet_snippets.sh
